### ISSUE TITLE
Crashes when used on a dedicated server

### ISSUE THREAD

**Issue by karltroid51** [hammertater/treechop#10]
Attached is the crash log.
Specific failure message indicates that treechop failed to load correctly, along with "java.lang.RuntimeException: Attempted to load class net/minecraft/client/multiplayer/PlayerController for invalid dist DEDICATED_SERVER".

[crash-2020-12-11_13.58.55-fml.txt](https://github.com/hammertater/treechop/files/5679523/crash-2020-12-11_13.58.55-fml.txt)

**Comment by hammertater** [comment]
Thanks for reporting this. Looks like I got sloppy when adding some keybinding configuration stuff in 0.9. I'll post a fixed 0.10 version soon. Sorry about that!

**Comment by hammertater** [comment]
0.10 is posted here and on CurseForge.

**Comment by karltroid51** [comment]
Thank you for the speedy fix! 🥇

**Comment by hammertater** [comment]
For sure! I'm gonna close this issue since it seems to be fixed. Keep the bug reports coming eh?
