### ISSUE TITLE
Stripped logs use default texture when chopped

### ISSUE THREAD

**Issue by niraqw15** [hammertater/treechop#101]
Chopping a stripped log will make it use the stripped oak texture instead of its own. Also, sideways stripped logs will use the texture of an upright log when chopped (top left chopped log in picture).

![2022-01-26_19 56 12](https://user-images.githubusercontent.com/22210045/151289935-a94e39d1-88a1-42e9-99ba-ecae6c2ec63d.png)
All logs in this tree were either Acacia or Stripped Acacia before chopping.

Minecraft: 1.18.1
Forge: 39.0.59
Mods: TreeChop-1.18.1-0.15.5

**Comment by hammertater** [comment]
Egads that’s ugly. Thanks for reporting, I’ll get it fixed
