### ISSUE TITLE
Chopped logs don't drop items

### ISSUE THREAD

**Issue by niraqw15** [hammertater/treechop#103]
Chopped logs don't give item drops, excluding the chopped log that the player last hit. For example, the tree in the screenshot is 6 logs tall, but only drops 3 logs when cut at the bottom.

![2022-01-31_00 00 14](https://user-images.githubusercontent.com/22210045/151758080-a287f250-fad9-41b1-adee-76e98771c95d.png)

Minecraft: 1.18.1
Forge: 39.0.59
Mods: TreeChop-1.18.1-0.15.5

**Comment by hammertater** [comment]
Thanks for reporting, I'll get it fixed

**Comment by hammertater** [comment]
Fixed in 0.15.6
