### ISSUE TITLE
Trying to chop a surrounded log destroys it

### ISSUE THREAD

**Issue by niraqw15** [hammertater/treechop#104]
Trying to chop a log that has blocks an all 6 sides of it instantly destroys it and doesn't drop anything. It also doesn't drop an item when the tree is cut down, but that might related to #103.

https://user-images.githubusercontent.com/22210045/151758989-af805fe8-60eb-4be7-85c8-737103cc02aa.mp4

Minecraft: 1.18.1
Forge: 39.0.59
Mods: TreeChop-1.18.1-0.15.5

**Comment by hammertater** [comment]
Thanks for the video, it really helps! I'll look into this

**Comment by hammertater** [comment]
In 0.15.6 chopping interior logs causes nearby logs to be chopped instead. The missing drops should be fixed too with #103.
