### ISSUE TITLE
Incompatibility with CarryOn-1.18.1-1.17.0.7

### ISSUE THREAD

**Issue by PaulerLeOne** [hammertater/treechop#105]
TreeChop-1.18.1-0.15.5
When trying to grab a chest with carryon, having the treechop mod, it will open the chest instead.
I'm not actually sure whether I should report this issue to this mod or to the carryon mod.

**Comment by hammertater** [comment]
Oops, look like an issue with TreeChop. It'll be fixed for next version. Thanks for reporting!

**Comment by jarocajavi** [comment]
I take a few days to locate the problem with carry on, finally i see is that mod, i hope you solve this soon, 2 mods so need in my server. https://github.com/Tschipp/CarryOn/issues/366

**Comment by hammertater** [comment]
Sorry for the wait. This should be fixed in 0.15.6
