### ISSUE TITLE
Multi Mine Support

### ISSUE THREAD

**Issue by Camawama** [hammertater/treechop#106]
When the mod Multi Mine is installed, the tree chopping does not work properly. 

I tried breaking the log and it just breaks like normal, however, if I slowly break it during the last few frames where it's breaking, it will work properly (kind of work).

**Comment by hammertater** [comment]
Sounds like it's on their end, but I'll take a look. Thanks for reporting!

**Comment by Camawama** [comment]
Yes, here is the mod list:

https://pastebin.com/RrSrZw0q

**Comment by hammertater** [comment]
Yeah, the problem is on MultiMine's end, there's not much I could/should do to fix it. In the meantime, you can disable MultiMine for trees by editing the multimine.cfg config file's `bannedBlocks` setting and adding `"treechop:choppables: true`, like so:
```
  "bannedBlocks": {
    "treechop:choppables": true
  },
```

**Comment by Stormalisk** [comment]
I tried the above for 1.16.5, but it seems like that isn't working. Tried that and ""treechop:chopped_log": true,"

**Comment by hammertater** [comment]
Ahh, I only tested on 1.18.2. I'll keep an eye out for a 1.16.5 solution. The author of MultiMine says the issue is fixed in 1.19 (TreeChop not available for 1.19 yet though) but won't be fixed in 1.18/1.16/earlier.

**Comment by hammertater** [comment]
Also, if you set `preventChopRecursion = false` in treechop's config under [compatibility.general], then instead of treechop not working on logs, they will get chopped twice. Which is still bad, but maybe a more desirable bug.

**Comment by Camawama** [comment]
I noticed that if you spam-click your mouse but time it every second, it will still chop the tree. It's actually a bit immersive so I consider this a desirable bug...but it still needs a little tweaking...

**Comment by Varshious** [comment]
You can also just add every log in your modpack to MultiMine's blacklist.

**Comment by hammertater** [comment]
Note that MultiMine only seems to cause issues with TreeChop on 1.18 and earlier. 1.19+ should be fine, per https://github.com/AtomicStryker/atomicstrykers-minecraft-mods/issues/440#issuecomment-1172895893

**Comment by Fizzy23** [comment]
Its still causing issues for me in 1.19.2

**Comment by hammertater** [comment]
Fixed in treechop 1.18.3+

**Comment by hammertater** [comment]
Issues came back. TreeChop 0.19.1 disables Multi Mine functionality while chopping.
