### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by GrizzGamez** [hammertater/treechop#112]
game crashes on 1.18.2 with this mod. please figure out a way to fix this

**Comment by hammertater** [comment]
Hi Grizz, thanks for reporting. When does the crash happen? And can you share a crash log?

**Comment by GrizzGamez** [comment]
As for the crash, it happens every time I load a world, I even tried a fresh world and same result. This is the crash log
[crash-2022-03-22_14.34.14-client.txt](https://github.com/hammertater/treechop/files/8337102/crash-2022-03-22_14.34.14-client.txt)

**Comment by hammertater** [comment]
Thanks for the log — looks like you actually have the 1.18.1 version of the mod installed. For some reason, CurseForge lists that above the 1.18.2 version, so it’s easy to mix them up. 1.18.2 is at https://www.curseforge.com/minecraft/mc-mods/treechop/files/3706945
