### ISSUE TITLE
Game crashing when breaking trees

### ISSUE THREAD

**Issue by massive-man** [hammertater/treechop#113]
I just downloaded the 1.18.2 version for forge. The game crashes immediately after breaking a log with the chop setting (normal breaking works normally)

Heres the crash message:

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'net.minecraftforge.registries.tags.ITagManager net.minecraftforge.registries.IForgeRegistry.tags()'
Exit-Code: -1

And the log:
[crash-2022-03-25_15.37.54-server.txt](https://github.com/hammertater/treechop/files/8351728/crash-2022-03-25_15.37.54-server.txt)

Thank you in advance.

Best egards,

Daniel

**Comment by hammertater** [comment]
Hi man, updating to Forge 40.0.18 or later should fix the crash

**Comment by massive-man** [comment]
Updating to forge 40.0.32 and n ow its working, thank you.

**Comment by hammertater** [comment]
Sweet! Any time big guy.
