### ISSUE TITLE
Tree chop doesn't work with Magma 1.16.5

### ISSUE THREAD

**Issue by omegadeltoro** [hammertater/treechop#114]
Hello, Me and my friend decided to play on minecraft server, I got myself a private server from Apexhosting. I wanted to play with forge and intalled a server client called Magma which is a mix of forge and paper (plugin software) But during our game tree chop wasn't working, the only feature which was working is: leaves breaking when breaking last log in the tree. All other features (except menu were disabled.  Cut blocks were appearing sometimes but then they became invisible and invincible.  The mod worked for me in single player.
Here are my logs:
[2022-04-06-2.log](https://github.com/hammertater/treechop/files/8431659/2022-04-06-2.log) 
Any idea what might be causing this? My server and game vesions are: 1.16.5

**Comment by hammertater** [comment]
Thanks for reporting. Could you give me a list of the mods you're using? It's not in the log. Also, have you tried running a Magma server with just TreeChop and no other mods? Right now I'm not sure if it's a Magma issue or a mod conflict.

**Comment by omegadeltoro** [comment]
![image](https://user-images.githubusercontent.com/74896799/162159940-89fc63be-9fd9-4a10-ae3a-c6726e69d3db.png)
here is my modpack. I also checked and the problem is due to Magma but without it my fps tanks from 500 to 40. Even without any other mods it doesent work on Magma but works on only forge servers. Is there any way to fix this?

**Comment by hammertater** [comment]
Hey, sorry for the wait. I still intend to look into this. I'll get back to you soon-ish

**Comment by ben001109** [comment]
i have the same question about this.

**Comment by hammertater** [comment]
I tested on a magma server with just TreeChop and it worked. @ben001109 could you show your list of mods? Maybe you and @omegadeltoro have a mod in common that's causing this

**Comment by ben001109** [comment]
I am using the modpack it called A Stack Neko²
Here is the modpack's link and the version is beta 0.7 and for the modpack's playable we template disable this mod in our mod pack's server and the single player games are no that problem.

**Comment by ben001109** [comment]
@hammertater and this is the modlist 
`html
<ul>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/waddles">Waddles (by Girafi)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/frozen-delight">Frozen Delight (A Farmer's Delight Add-on) (by nocubeyt)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/just-enough-resources-jer">Just Enough Resources (JER) (by way2muchnoise)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/serene-seasons">Serene Seasons (by TheAdubbz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/illagers">Illagers+ (by LiteWolf101)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create">Create (by simibubi)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/dungeonsenhanced">Dungeons Enhanced (by Valarauko9)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ticbc">TiCBC - Tinkers Better Compat (by ianm1647)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-third-person">Better Third Person (by Socolio)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/collective">Collective (Forge) (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/colytra">Colytra (Forge) (by TheIllusiveC4)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/structure-gel-api">Structure Gel API (by ModdingLegacy)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/regrowth">Regrowth (by MacTso)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/easy-magic">Easy Magic [Forge] (by Fuzs_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jei-enchantment-info">JEI Enchantment Info (by Phylogeny)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/healing-campfire">Healing Campfire (Forge) (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/stoneholm-forge">Stoneholm, Underground Villages (Forge) (by TheGrimsey)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/merchant-markers">Merchant Markers (by Grend_G)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/bedspreads">Bedspreads (Forge) (by TheIllusiveC4)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/buried-barrels">Buried Barrels (by Aureljz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/big-brain">Big Brain (by almightytallestred)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/enhanced-celestials">Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance">Better Fps - Render Distance[Forge] (by someaddon)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/frozen-up">Frozen Up (by ninnih_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/buzzier-bees">Buzzier Bees (by TeamAbnormals)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/terraforged">TerraForged (by won_ton_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mo-structures-forge">Mo' Structures (Forge) (by ffrannny)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mattdahepic-core">MattDahEpic Core (MDECore) (by MattDahEpic)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/farmers-delight-cookbook-addon">Farmer's Delight Cookbook Addon [0.4 is the last update] (by dalumma)</a></li>
<li><a href="https://www.curseforge.com/minecraft/texture-packs/better-ender-dragon">Better Ender Dragon (by Ricy41)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/blueprint">Blueprint (by TeamAbnormals)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/repurposed-structures">Repurposed Structures (Forge) (by telepathicgrunt)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/waystones">Waystones (by BlayTheNinth)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/optiforge">OptiForge (by ZekerZhayard)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cleancut">CleanCut (by Rongmario)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/comforts">Comforts (Forge) (by TheIllusiveC4)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/flywheel">Flywheel (by jozufozu)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ichunutil">iChunUtil (by ohaiiChun)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/back-tools">Back Tools (by ohaiiChun)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/second-chance-forge">Second Chance (Forge) (by InfernalStudios)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jumpy-boats">Jumpy Boats (by LobsterJonn)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/bookshelf">Bookshelf (by DarkhaxDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm">L_Ender 's Cataclysm (by mcl_ender)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/paragliders">Paragliders (by Tictim)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-than-mending">Better Than Mending (by legobmw99)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/sky-villages-forge">Sky Villages [Forge] (by y4z0n)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/majrusz-library">Majrusz Library (by Majrusz17)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/global-xp">Global XP (by bl4ckscor3)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/rotten-piglins-mod">Rotten Piglins Mod(Forge) (by abukkezsaruj)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/lazy-dfu-forge">Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/better-mods-button">Better Mods Button [Forge] (by Fuzs_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/advancement-plaques">Advancement Plaques (by Grend_G)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-api">YUNG's API (Forge) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/corpse">Corpse (by henkelmax)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/connectible-chains-forge">Connectible Chains [FORGE] (by lilypuree)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-dragons">Ice and Fire: Dragons (by sbom_xela)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/anvil-restoration">Anvil Restoration (Forge) (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/chocolate-fix">Chocolate Fix (by AlcatrazEscapee)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/crafttweaker">CraftTweaker (by Jaredlll08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/champions">Champions (by TheIllusiveC4)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/wonderful-enchantments">Wonderful Enchantments (by Majrusz17)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/advanced-finders">Advanced Finders (by EnderLanky)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/stalwart-dungeons">Stalwart Dungeons (by Furti_Two)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-caves">YUNG's Better Caves (Forge) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cobbler">Shulker's Faithful Factories (Previously Cobbler) (by britishnickk)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/travelers-titles">Traveler's Titles (Forge) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/farmers-delight">Farmer's Delight (by vectorwing)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/configured">Configured (by MrCrayfish)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/smaller-nether-portals">Smaller Nether Portals (Forge) (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/tinkers-delight">Tinker's Delight (by chirptheboy)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/astikorcarts">AstikorCarts [Horse Carts] (by pau101)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/treechop">HT's TreeChop (by hammertater)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mantle">Mantle (by mDiyo)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/falling-leaves-forge">Falling Leaves (Forge) (by Cheaterpaul)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/itemphysic-lite">ItemPhysic Lite (by CreativeMD)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/puzzles-lib">Puzzles Lib [Forge] (by Fuzs_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty">Biomes O' Plenty (by Forstride)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/controlling">Controlling (by Jaredlll08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/forgiving-void">Forgiving Void (by BlayTheNinth)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/antique-waystones">Antique Waystones (by HorribleNerd)</a></li>
<li><a href="https://www.curseforge.com/minecraft/texture-packs/embellished-stone-advancement-plaques">Embellished Stone (Advancement Plaques) (by Grend_G)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/chunk-animator">Chunk Animator (by Lumien231)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/blood-magic">Blood Magic  (by WayofTime)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/forgeendertech">ForgeEndertech (by EnderLanky)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/illagers-wear-armor">Illagers Wear Armor (by almightytallestred)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions">Enchantment Descriptions (by DarkhaxDev)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ferritecore">FerriteCore (Forge) (by malte0811)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge">Kotlin for Forge (by thedarkcolour)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cultural-delights">Cultural Delights (by NCP_Bails)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/endremastered">End Remastered (by jack_bagel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/more-villagers">More Villagers (by SameDifferent)</a></li>
<li><a href="https://www.curseforge.com/minecraft/texture-packs/fresh-animations">Fresh Animations (by Fresh__LX)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/appleskin">AppleSkin (by squeek502)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/auto-ore-dictionary-converter">Auto Ore Dictionary Converter (by MattDahEpic)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/bountiful">Bountiful (Forge) (by ejektaflex)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/guard-villagers">Guard Villagers (by almightytallestred)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jei">Just Enough Items (JEI) (by mezz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/chunkpregenerator">Chunk-Pregenerator (by Speiger)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/antique-dragons">Antique Dragons (by Samlegamer_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/cloth-config">Cloth Config API (Fabric/Forge) (by shedaniel)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/mowzies-mobs">Mowzie's Mobs (by bobmowzie)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/inventory-tweaks-renewed">Inventory Tweaks Renewed (by godemperordoge)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/caelus">Caelus API (Forge) (by TheIllusiveC4)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/config-menus-forge">Config Menus for Forge (by Fuzs_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/tinkers-archery">Tinkers' Archery (by tonitetwitch)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/patchouli">Patchouli (by Vazkii)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/charm-reforged">Charm Reforged (by svenhjol)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/iceberg">Iceberg (by Grend_G)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons">YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/piglin-expansion">Piglin Expansion (by Ddx11__)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/farmers-delight-compats">Farmer's Delight Compats (by burritoeatinghamster)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/create-confectionery">Create Confectionery (by Furti_Two)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/ice-and-fire-tweaker">Ice And Fire Tweaker (by Jaredlll08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/texture-packs/all-new-1-17-textures">All New Caves & Cliffs Textures (by doodooxyz)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/createtweaker">CreateTweaker (by Jaredlll08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/creativecore">CreativeCore (by CreativeMD)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/world-pre-generator">World Pre Generator (by GeheimagentNr1)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/towers-of-the-wild-reloaded">Towers of the Wild: Reloaded (by yuesha_yc)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/dynamic-surroundings">Dynamic Surroundings (by OreCruncher)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/clumps">Clumps (by Jaredlll08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/texture-packs/ice-fire-dragonsteel-weaponry">Ice & Fire Dragonsteel Weaponry (by DE4THR4SH)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/geckolib">GeckoLib (by ThanosGecko)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/villager-names">Villager Names (Forge) (by Serilum)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/citadel">Citadel (by sbom_xela)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/natures-compass">Nature's Compass (by Chaosyr)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/nekos-enchanted-books">Neko's Enchanted Books (by Nekomaster1000)</a></li>
<li><a href="https://www.curseforge.com/minecraft/texture-packs/motschens-better-leaves">Motschen's Better Leaves (by Motschen)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/antique-atlas">Antique Atlas (by Hunternif)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/goblin-traders">Goblin Traders (by MrCrayfish)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jeitweaker">JEITweaker (by Jaredlll08)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/jade">Jade 🔍 (by Snownee_)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/betterend-forge-port">BetterEnd (Forge) (by Beethoven92)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/spiders-2-0">Spiders 2.0 (by TheCyberBrick)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/tinkers-construct">Tinkers Construct (by mDiyo)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/sapience">Sapience (by the_infamous_1)</a></li>
<li><a href="https://www.curseforge.com/minecraft/mc-mods/creatures-and-beasts">Creatures and Beasts (by joosh_7889)</a></li>
</ul>
`

**Comment by hammertater** [comment]
Actually, TreeChop doesn't work on Magma for 1.16.5. Working on it. I may need to report this to the Magma devs.

**Comment by hammertater** [comment]
The problem is on Magma's end. https://git.magmafoundation.org/magmafoundation/Magma-1-16-x/-/issues/14

**Comment by hammertater** [comment]
Ok, I think they fixed it! You'd need to upgrade to the latest version of Magma for 1.16.5
