### ISSUE TITLE
Incompatibility with modest beginnings (1.16.5)

### ISSUE THREAD

**Issue by NixityNull** [hammertater/treechop#116]
This mod bypasses Modest beginnings's requirement to use an axe in order to break wood

Modest Beginnings (https://www.curseforge.com/minecraft/mc-mods/modest-beginnings)

**Comment by hammertater** [comment]
Ack! Sorry for not replying. I'll look into it. Thanks for reporting!

**Comment by hammertater** [comment]
The mod author says it has been discontinued, and source is not available to figure out how to fix it. Leaving open in case others run into this issue
