### ISSUE TITLE
compat with enlightened end

### ISSUE THREAD

**Issue by alexstanleeee** [hammertater/treechop#117]
With Enlightened end, the mod works, however the texture resembles that of a stripped oak log. I have submitted this issue to them toom, as I'm unsure which mod can fix it.

**Comment by hammertater** [comment]
Thanks for reporting! Probably Enlightened End didn’t make or didn’t correctly register a
stripped versions of their logs. When that happens, treechop defaults to the oak texture

**Comment by hammertater** [comment]
Enlightened end issue: https://www.curseforge.com/minecraft/mc-mods/enlightened-end/issues/10

**Comment by hammertater** [comment]
From the issue,
> I am unable to fix because of MCreator restrictions.
