### ISSUE TITLE
Compat Enlightened End P2

### ISSUE THREAD

**Issue by alexstanleeee** [hammertater/treechop#119]
Following my previous report of Enlightened End not functioning correctly with the mod 'Enlightened End', I reported it to them in the hopes it could be fixed though I discovered that due to the mod being made with MCreator, and due to MCreator's restrictions it could not be fixed. I wondered if it was possible for me to fix myself with some sort of third-party compat mod, or if you would consider adding compat in a later version due to the mod's popularity?
Thanks so much,
Ales

**Comment by hammertater** [comment]
I see some compat mods for Fabric that could let you fix it, but not for Forge. But yeah, I can add compatibility 👍

**Comment by hammertater** [comment]
Tested in 1.18.2 and 1.19.2, seems to be working. Closing, feel free to open if there are still issues.
