### ISSUE TITLE
[Suggestion] Consider adding Jade support for 1.18.2

### ISSUE THREAD

**Issue by GeorgeOrwell1** [hammertater/treechop#122]
I know that maintaining old versions and stuff is very hard and time-consuming. I understand that but I'd really appreciate it if you could add Jade support to 1.18.2 as well as that still is considered an LTS version which many people still use and probably will use until popular mods like Create get updated to 1.19.

**Comment by hammertater** [comment]
Hey George, I didn't release JADE support for 1.18.2 because it seems to cause crashes when other WAILA forks (like WTHIT) are loaded. Not sure yet whether to just assume everyone uses JADE, or to make a separate "treechop jade support" mod.

**Comment by KyrDerz** [comment]
Tbh making support for either of those two will come a long way. Basically, I'd be switching to the fork that has the support. Jade or WTHIT are almost perfect substitutes. Right now on Jade the normal icon appears. But on WAILA it's broken altogether. So I guess I'm using Jade.

**Comment by hammertater** [comment]
Oops, forgot to update this issue. Separate Jade and WTHIT plugins were posted on CurseForge some time ago:
- https://www.curseforge.com/minecraft/mc-mods/treechopjade
- https://www.curseforge.com/minecraft/mc-mods/treechopwthit
