### ISSUE TITLE
Bamboo is choppable Forge 1.19.1

### ISSUE THREAD

**Issue by DaddySpin** [hammertater/treechop#123]
It seems that bamboo is a choppable block because it is tagged as #minecraft:logs and it does not work properly.
the below picture shows what I mean.
![2022-08-08_01 51 55](https://user-images.githubusercontent.com/34575655/183357277-f38d66e7-0eea-4262-8684-a6e61a07c93a.png)
![2022-08-08_01 58 43](https://user-images.githubusercontent.com/34575655/183358261-f225eb21-f274-4251-b272-f4983abb150d.png)

**Comment by hammertater** [comment]
Yikes, thanks for reporting! I'll get it fixed

**Comment by hammertater** [comment]
Actually, I don't see this happening on my end. Maybe another mod is adding the logs tag to bamboo? (sorry for the wait)

**Comment by hammertater** [comment]
@DaddySpin did you have William Wyther's Overhauled Overworld installed? (https://www.curseforge.com/minecraft/mc-mods/william-wythers-overhauled-overworld) If so, that's what's making bamboo get chopped (https://github.com/hammertater/treechop/issues/142#issuecomment-1318049608)

Will be fixed when #126 is implemented

**Comment by DaddySpin** [comment]
Yeah I use WWOO it makes the game so nice when mixed with teralith and BOP.
