### ISSUE TITLE
0.15.8 on 1.18.2

### ISSUE THREAD

**Issue by KyrDerz** [hammertater/treechop#124]
That WTHIT support would go a long way on 1.18.2 version of the mod

**Comment by hammertater** [comment]
I tried, but adding WTHIT in 1.18.2 seems to cause Jade to crash. Do you know of any mods that support both? Or a mod that supports WTHIT and doesn't crash Jade, or vice versa?

As a last resort, I could make a separate compat mods for WTHIT and Jade.

**Comment by KyrDerz** [comment]
To be honest no idea. But separate would be pretty great. Since it's always one or the other. Also 1.18.2 player base is super huge so we will appreciate it :)
