### ISSUE TITLE
Redwood Lag

### ISSUE THREAD

**Issue by reddvilzz** [hammertater/treechop#125]
Using 1.12.2 with HT's TreeChop 0.14.6

When looking at BoP Redwood Tree's Wood from the bottom of it will reduce my fps from 100 into 20 or sometimes even lower to 10.

If I look at the Redwood Tree's from the middle the fps is slightly higher around 40 - 50.

The logs doesn't show anything. What can I do to help diagnose it?

**Comment by hammertater** [comment]
Hey Red, you can eliminate the fps hit by disabling the chop indicator (press n by default to open the mod settings, then click the two dots at the bottom to show advanced settings).

The indicator is not very optimized at the moment, especially on 1.12.2

**Comment by reddvilzz** [comment]
> Hey Red, you can eliminate the fps hit by disabling the chop indicator (press n by default to open the mod settings, then click the two dots at the bottom to show advanced settings).
> 
> The indicator is not very optimized at the moment, especially on 1.12.2. TreeChop looks for leaves connected to the block you’re looking at, and that takes longer to do for bigger trees

Okay thanks, that fixed it.

**Comment by Wubzzz1337** [comment]
I do this, but it still lags, is there any kind of other fix? 
Or could this be related to maxing out the "Max" items it can chop in the config? I set it to 8000+.
It lags whenever you look at big trees and change the log blocks on it.
