### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by coppalka** [hammertater/treechop#127]
Fabric 1.19.2 + Sodium + Iris give me crash after i install mod
[crash-2022-09-29_20.55.26-client.txt](https://github.com/hammertater/treechop/files/9675458/crash-2022-09-29_20.55.26-client.txt)

**Comment by hammertater** [comment]
Oops! I forgot to mention that TreeChop on Fabric requires Forge Config API Port: https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric/files/3527042

**Comment by coppalka** [comment]
> Oops! I forgot to mention that TreeChop on Fabric requires Forge Config API Port: https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric/files/3527042

Thanks a lot, but theres a problem. Together with indium mod crashes the game when chop tree. 
[crash-2022-09-30_00.34.03-client.txt](https://github.com/hammertater/treechop/files/9677824/crash-2022-09-30_00.34.03-client.txt)

Without it, it looks like in the screenshot.
![2022-09-30_00 43 06](https://user-images.githubusercontent.com/96778859/193104346-452f7da9-8ca5-46d8-96ca-1f07f236b626.png)

**Comment by hammertater** [comment]
Thanks for all the info. I'll get this fixed asap.

**Comment by hammertater** [comment]
From https://www.curseforge.com/minecraft/mc-mods/sodium:
> Sodium is mostly stable at this point, but it does not yet contain support for the Fabric Rendering API, which a small number of mods currently use. If you try to use these mods with Sodium, your game may crash or behave unexpectedly.

TreeChop is using the Fabric rendering API. I'll see if I can do without it.

**Comment by coppalka** [comment]
Sounds like a big problem... Thanks you for support, i wish you success with this problem

**Comment by hammertater** [comment]
No problem, thanks for reporting :) Version 0.16.1 is posted on CurseForge, it should fix the visual issues and crashes.
