### ISSUE TITLE
Crash while playing Triforge

### ISSUE THREAD

**Issue by WarrenOC** [hammertater/treechop#129]
I was getting into a modpack I found called Triforge (v1.5.2) and I went to cut down a tree that had some branches after it got to the second log up, where the branches were, it crashed. The modpack uses 1.18.2-0.15.7 If anymore information is needed I would be glad to provide it.

**Comment by WarrenOC** [comment]
Sorry for taking so long I've been quite busy. Also thank you for the guide I wish more people did stuff like that. (I use PolyMC though lol)
[latest.log](https://github.com/hammertater/treechop/files/9720985/latest.log)
[debug.log](https://github.com/hammertater/treechop/files/9720987/debug.log)

**Comment by hammertater** [comment]
Sorry, forgot about this... Thanks for the logs! Turning off the chop indicator might prevent the crash. I probably won't be able to fix the root issue for a week or two.

**Comment by hammertater** [comment]
Note to self: in `ht.treechop.client.gui.util.Sprite`. line 40-ish, `RenderSystem.setShader(GameRenderer::getPositionTexShader);` , `GameRenderer::getPositionTexShader` is probably the culprit.

**Comment by hammertater** [comment]
Also, I'd guess that the crash is happening because of a graphics-related mod (shaders, fps boosters, etc.). Does the game crash every time something gets "chopped"? Or maybe only for specific types of log blocks? Any context like that would help a lot.

**Comment by WarrenOC** [comment]
I haven't been on for a while but no it does not crash every time it was once but I had to make a new world afterwords. Also I don't remember what mods were in the pack before because it just got a massive overhaul. As of now the mods that seem to match your description are: BetterFPS, CamerOverhaul(Maybe, i dont think tho), Connected Textures Mod, Flywheel, GeckoLib, Radium Reforged, Rubidium, Rubidum Extra, and Iris. If some of these mods make no sense at all to be causing the problem I literally just put every mod that said rendering or was a fork of something I knew was for rendering, I don't actually know what they do.

**Comment by hammertater** [comment]
The crash is most likely related to Iris. Compatibility with Sodium + Iris was added in treechop 0.16.1 for minecraft 1.18.2. It completely changes how chopped logs are rendered, so most likely this is fixed. The latest version of triforge "2.4 Beta" uses treechop 0.16.3
