### ISSUE TITLE
Rendering issue (Starlight incompat)

### ISSUE THREAD

**Issue by FluffyBumblebees** [hammertater/treechop#130]
When the **First** stripped log pops in, all HT's tree chop rendering for the custom chopped "stripped" logs  are black where the block faces should be.

on Fabric
https://gist.github.com/FluffyBumblebees/3b370010b62e26d6a187ac5bfb7fed54

**Comment by FluffyBumblebees** [comment]
![image](https://user-images.githubusercontent.com/60066663/194330601-703e295d-e306-48cb-ac2b-7ac1bab70ae6.png)

**Comment by hammertater** [comment]
Bummer, thought I fixed this (it used to also crash: #127). Thanks for reporting. I'll look into it tonight

**Comment by hammertater** [comment]
Could you try updating Sodium? I see you're using 0.4.1, but when I attempted to fix this I was using 0.4.4 (the latest, 0.4.https://www.curseforge.com/minecraft/mc-mods/sodium/files/3957319)

**Comment by FluffyBumblebees** [comment]
I nailed it down to incorrect shadows. If I shine light on it via a shaderpack, it doesnt look black.

**Comment by FluffyBumblebees** [comment]
If I place a light next to it, without shaders. the light update alone makes it appear dark.

**Comment by FluffyBumblebees** [comment]
Could be starlight perhaps

**Comment by FluffyBumblebees** [comment]
It's starlight

**Comment by hammertater** [comment]
Thanks, that helps a lot. I’ll see if I can add compatibility with starlight

**Comment by hammertater** [comment]
Sorry, forgot to share here -- this should be fixed in 0.16.3

**Comment by FluffyBumblebees** [comment]
Yes, it's fixed. I tested! Everything works perfectly now. Thanks!
