### ISSUE TITLE
Treechop causes dropped blocks to not render

### ISSUE THREAD

**Issue by Yhoundeh** [hammertater/treechop#135]
I am using treechop 0.16.3 on Minecraft 1.18.2 fabric. Whenever I dropped a stack of any blocks (q) the blocks would fail to appear until I backed away ten or so blocks after-which they behaved normally. Furthermore if I don't back away to "reset" them they make no noise when I walk up to pick them up. They simply appear in my hotbar.

Context: I'm building a mod pack so this _could_ be a compatibility problem but in my attempt to find the culprit I eliminated quite a few mods from the pack. However, adding treechop back always caused the problem to occur. (As I think about it it might be immersive portals or indium doing it.)

Here's one of the logs:
[2022-10-13-2.log](https://github.com/hammertater/treechop/files/9783162/2022-10-13-2.log)

**Comment by hammertater** [comment]
Hey, thanks for sharing. It sounds like a desync issue, where items only get synced when you enter a different world chunk. I can’t imagine treechop causing this. I would guess that it’s related to C2ME, maaaybe immersive portals, probably not indium

**Comment by Yhoundeh** [comment]
Hmm okay, C2ME was giving me issues with immersive portals so I removed it. I am having connection issues so that could very well be it. I'll fiddle around with it for a bit and see if I can get more hard results. Marking as closed then.

**Comment by hammertater** [comment]
Sounds good, good luck!
