### ISSUE TITLE
One of the 1.19.2 Fabric versions shows up as the latest Forge version on Curseforge

### ISSUE THREAD

**Issue by pouchrat** [hammertater/treechop#138]
(... and also doesn't yell at you when you try to load it in a Forge game.)

This version:
[TreeChop-1.19.1-fabric-0.16.0.jar](https://www.curseforge.com/minecraft/mc-mods/treechop/files/4010205)

![image](https://user-images.githubusercontent.com/38634418/197402252-a6492d04-3514-4bd7-93d8-b9e46a32d4c6.png)

**Comment by hammertater** [comment]
Ahhh thanks for pointing out the perp. I added the tag, hopefully the issue is fixed?
