### ISSUE TITLE
Frequent warnings in 1.18.2: NBT contains bad sneak behavior value ""; using default value instead

### ISSUE THREAD

**Issue by LukeZaz** [hammertater/treechop#145]
Almost identically to #70, I'm getting loads of the following error in server logs whenever TreeChop is installed:

`[Server thread/WARN]: NBT contains bad sneak behavior value ""; using default value instead`

This happens constantly in the logs, seemingly mostly when new chunks are loaded. Example:

![image](https://user-images.githubusercontent.com/5722543/203922003-0b23793f-7c6b-4c78-ad34-d1aa98599d09.png)
(note that this screenshot is from a singleplayer test, but it happens on dedicated servers as well with similar frequency)

I'm running Minecraft 1.18.2 with Fabric Loader 0.14.10. The only mods installed are Fabric API 0.66.0, Forge Config API Port 3.2.4, and TreeChop 0.16.3.

**Comment by hammertater** [comment]
Sorry for the wait. The messages should be greatly reduced in treechop 0.17.0 for minecraft 1.19.2. I'll be sure to port the fix to 1.18.2 as soon as I can.

**Comment by hammertater** [comment]
Ported to 1.18.2, closing
