### ISSUE TITLE
[Incompatibility] Terrestria and HT's TreeChop - crashing clients

### ISSUE THREAD

**Issue by TheyCallMeToast** [hammertater/treechop#146]
Pack: Medieval Minecraft 1.19.2 [Fabric]

Issue: When chopping down a sakura tree with an axe, the axe activates HT's Tree Chop mod and crashes the client of the person that chopped the tree. (HT Tree Chop adds different phases of trunk thickness while chopping).
Crash log for the client that chopped the sakura tree: [crash-2022-11-27_18.03.35-client.txt](https://github.com/hammertater/treechop/files/10099670/crash-2022-11-27_18.03.35-client.txt)

In addition, it creates a rendering bug that also crashes any player within render distance as well.
In the area of affect crash log:
[crash-2022-11-27_18.58.30-client.txt](https://github.com/hammertater/treechop/files/10099672/crash-2022-11-27_18.58.30-client.txt)

I know that this could be an issue with either mod, so I am creating a ticket on both mods' Github pages.
Thank you for all your hard work and for being active within the community!

p.s. We have been playing Medieval MC for about a month and in previous versions, we could use Tree Chop with sakura trees without an issue, therefore we are thinking it may be something that was changed in the last month. Hope all the information helps narrow the issue and solution!

**Comment by FluffyBumblebees** [comment]
can confirm its happening on 1.18.2

**Comment by hammertater** [comment]
Sorry for the wait, this should be fixed in 0.17.0 for minecraft 1.19.2. I'll be sure to port the fix back to 1.18.2 in the near future

**Comment by FluffyBumblebees** [comment]
All good. No pressure, thanks for this awesome mod!

**Comment by hammertater** [comment]
Ported to 1.18.2, closing
