### ISSUE TITLE
crash in the client 1.19.2

### ISSUE THREAD

**Issue by papillo12** [hammertater/treechop#147]
several people reported to me that when they saw spawm the game crashed
[crash-2022-11-28_20.45.39-client.txt](https://github.com/hammertater/treechop/files/10109154/crash-2022-11-28_20.45.39-client.txt)

**Comment by hammertater** [comment]
Hey, sorry about that. It's the same issue as #142 and will be fixed in the next update. It happens with some modded logs. Do you know what type of log block is causing the crash? Or can you point me to your modpack so I can try to figure it out myself?

**Comment by papillo12** [comment]
it was not a specific block, they only saw the spawm and the game crashed.

**Comment by hammertater** [comment]
Should be fixed in 0.17.0, sorry for the wait
