### ISSUE TITLE
Crash on latest version 1.19.2

### ISSUE THREAD

**Issue by zacharyboland** [hammertater/treechop#149]
[crash-2022-12-08_19.21.59-client.txt](https://github.com/hammertater/treechop/files/10190795/crash-2022-12-08_19.21.59-client.txt)

**Comment by hammertater** [comment]
That's odd, the latest version didn't mess that bit of the code that's blamed for the crash. Could you also share the full log, not just the crash log? Maybe something went wrong before the crash

**Comment by zacharyboland** [comment]
[latest.log](https://github.com/hammertater/treechop/files/10191705/latest.log)
Here you go

**Comment by hammertater** [comment]
Thanks for the quick reply. Nothing stands out, I'll look further into it tomorrow

**Comment by WenXin20** [comment]
Hello, I had the same crash when trying to join my server after updating to v0.17.0
https://bytebin.lucko.me/N8aG0KxVk5

**Comment by Jukabofy** [comment]
[crash-2022-12-09_10.32.18-client.txt](https://github.com/hammertater/treechop/files/10196057/crash-2022-12-09_10.32.18-client.txt)
Looks like i have the same crash too

**Comment by miuirussia** [comment]
Confirm crash when join to world

**Comment by aelfwyne** [comment]
Same crash.

**Comment by hammertater** [comment]
Oof, sorry about that. The crash should be fixed in 0.17.1 (will be available in a few minutes on CurseForge)
