### ISSUE TITLE
Repeatable crash 1.19.2

### ISSUE THREAD

**Issue by aelfwyne** [hammertater/treechop#151]
Client crash when trying to chop trees. It has been working without issue until today, but now it crashes any time I try to chop a tree.

https://paste.ee/p/carOQ - Logfile.

**Comment by hammertater** [comment]
Looks like the CarryOn compatibility is failing. Switching back to TreeChop 1.16.3 (or earlier) should fix the crashes for now. I'll get this fixed asap

**Comment by hammertater** [comment]
Using an older version of CarryOn should also fix it - for example https://www.curseforge.com/minecraft/mc-mods/carry-on/files/4110529

**Comment by hammertater** [comment]
Ok, should be fixed in 0.17.2
