### ISSUE TITLE
Swap chop-icon depending on main hand

### ISSUE THREAD

**Issue by thimblebird** [hammertater/treechop#153]
Right hand:
![2022-12-18_19 50 20](https://user-images.githubusercontent.com/93487547/208314179-4cb24c34-a9ea-4ca8-bd08-35fcf1639e33.png)

Left hand:
![2022-12-18_19 49 54](https://user-images.githubusercontent.com/93487547/208314184-f3b150bf-e857-46fe-b6ae-77a89387d93c.png)

**Comment by hammertater** [comment]
To clarify, are you suggesting to move the icon to the left of the cursor for left-handed players? If so, the `treechop-client.toml` config should let you change the icon's position manually: under `[visuals.choppingIndicator]`, try setting `xOffset = -16`.

I could add support though. Maybe also flip the icon horizontally?

**Comment by thimblebird** [comment]
oh, yes; it should be dynamic based on the selected main hand. there's an identical feature in jade:
![image](https://user-images.githubusercontent.com/93487547/208542033-f227d4c9-c797-4278-a952-a86fc860e368.png)

flipping the axe icon would also be neat i think!

**Comment by hammertater** [comment]
Added in 0.17.3
