### ISSUE TITLE
Caupona chopped logs renders incorrectly

### ISSUE THREAD

**Issue by WenXin20** [hammertater/treechop#155]
`Minecraft v1.19.2`
`Forge v43.2.0`
`Tree Chop v0.17.2`
[`Caupona v0.2.1`](https://www.curseforge.com/minecraft/mc-mods/caupona)

I've noticed that the chopped log with Caupona's trees use an incorrect texture map instead of using the original block model. Though this might fixed once https://github.com/hammertater/treechop/issues/136 is fixed

![image](https://user-images.githubusercontent.com/12000593/209268604-70da96d3-145e-4256-8c3a-11fd8ffef21e.png)

**Comment by hammertater** [comment]
Nice catch, I’ll see if I can fix this on my end

**Comment by hammertater** [comment]
This should be fixed in 0.17.3. Note that the developer of Caupona may be adding treechop support in the future to fix the chopped log size and textures.
