### ISSUE TITLE
Transparent trunk

### ISSUE THREAD

**Issue by tapioca178** [hammertater/treechop#158]
When I chop the tree in Fabric 1.19.2 the trunk gets transparent.
![2022-12-22_15 54 53](https://user-images.githubusercontent.com/121298578/209342666-b199ca92-65f1-442d-b95b-c3b57e56a514.png)

**Comment by hammertater** [comment]
Thanks for posting here. Could you share a log file? If you're using a mod pack, can you send me a link to it?

**Comment by hammertater** [comment]
Might be fixed in 0.17.6, will try to test later.

**Comment by hammertater** [comment]
I'm pretty sure this is fixed in newer versions of TreeChop. Feel free to reopen if you're still having issues
