### ISSUE TITLE
[1.18.2] Crash with Dynamic Trees

### ISSUE THREAD

**Issue by itsdinkd** [hammertater/treechop#159]
Describe the bug
No idea how to describe the bug. Crashed after witch was throwing potions at me

To Reproduce
I went into my modpack, AQM3, with Dynamic Trees and Dynamic Trees Plus added.
Join existing world
summoned a witch and was letting it throw potions at me (for another mod test)
crashed 5 seconds later

Additional context

Crashes
DynamicTrees-1.18.2-0.11.0-Beta5.jar
https://gist.github.com/itsdinkd/a9ac7ebd686c252ec64537eb73e78dd9

DT Issue https://github.com/DynamicTreesTeam/DynamicTrees/issues/746

**Comment by hammertater** [comment]
Should be fixed in 0.17.3
