### ISSUE TITLE
Crash with Project MMO

### ISSUE THREAD

**Issue by NerdyViking** [hammertater/treechop#162]
[crash-2023-01-24_12.25.19-server.txt](https://github.com/hammertater/treechop/files/10485608/crash-2023-01-24_12.25.19-server.txt)

Game crashed when using Project MMO. Disabling the compatibility in the settings file makes it not crash anymore, but you can't get any XP from chopping logs anymore. Adjusting from block xp to override and adjusting the values doesn't seem to do anything else.

**Comment by hammertater** [comment]
Hey, sorry about the crashes. Just waiting for Project MMO to get an update (#161), then I'll update TreeChop with a fix.

**Comment by hammertater** [comment]
I've disabled Project MMO support in TreeChop 0.17.3. I'll bring back support when Project MMO fixes some things on their end.
