### ISSUE TITLE
[1.18.2] Stuck during world generation process with latest mod version

### ISSUE THREAD

**Issue by SirZokxyron** [hammertater/treechop#163]
This was concluded with only the HT Tree Chop mod in the mod folder.

Mod version: TreeChop-forge-1.18.2-0.17.3.jar
Forge version: 40.2.1
Minecraft logs: https://mclo.gs/8jneNPd

It spams the logs with the same error message : "Duplicate Capability Key: minecraft:treechopchop_settings_capability"

**Comment by hammertater** [comment]
Grrr. Sorry about that, I’ll get it fixed

**Comment by hammertater** [comment]
Hopefully fixed in 0.17.3b, just posted.

**Comment by SirZokxyron** [comment]
Fixed indeed!
Thank you very much!
