### ISSUE TITLE
[1.18.2] Issue with Jade Plugin

### ISSUE THREAD

**Issue by SirZokxyron** [hammertater/treechop#164]
There's an issue of display when using the HT's TreeChop - Jade Plugin.

Forge version : 40.2.1
Mod used during the test : 
- TreeChop-forge-1.18.2-0.17.3b.jar
- TreeChop-Jade-1.18.2-forge-0.1.0.jar
- Jade-1.18.2-forge-5.2.6.jar
- JadeAddons-1.18.2-forge-2.4.1.jar

Pictures with the addon
![with_plugin_log](https://user-images.githubusercontent.com/25960628/216102847-a141712b-6b0a-4741-b666-9701c4af25e6.png)
![with_plugin_other](https://user-images.githubusercontent.com/25960628/216102843-52ae558b-4c7a-4f19-b21f-56875496cc08.png)

Pictures without the addon
![without_plugin_log](https://user-images.githubusercontent.com/25960628/216102981-14acd287-5a14-45b1-9ce3-135e5b3aad0f.png)
![without_plugin_other](https://user-images.githubusercontent.com/25960628/216102987-c82643ed-5a17-488e-8467-01b90fbf00ac.png)

**Comment by hammertater** [comment]
Thanks for reporting, should be fixed in plugin version 0.1.1

**Comment by SirZokxyron** [comment]
It's fixed indeed, once again, thank you very much!
