### ISSUE TITLE
Update from 0.16.3 to 0.17.3b results in clientside crashes when an old half chopped block is loaded

### ISSUE THREAD

**Issue by abovearth** [hammertater/treechop#166]
We play on a server. We have updated the mod on server and client from 0.16.3 to 0.17.3b. When a player loads a treechop:chopped_log block, by walking around or teleporting around, Their game crashes with the following error:
[crash-2023-02-02_16.22.16-client.txt](https://github.com/hammertater/treechop/files/10688951/crash-2023-02-02_16.22.16-client.txt)

What we do to solve this now, as the number of blocks is quite low, is from console:

Assuming that the problematic location is 423 95 -1047:
fill 423 95 -1047 423 95 -1047 minecraft:oak_log replace treechop:chopped_log
if that complains about the location not being loaded run commands:
forceload add 423 -1047 
and then the fill command again. When the fill command is succesfull it will return:
[21:43:30] [Server thread/INFO] [minecraft/DedicatedServer]: Successfully filled 1 blocks
afterward remove the forced loading with 
forceload remove 423 -1047

or in game from somewhere else on the server using worldedit
//pos1 -224,-64,-3088
//pos2 -209,319,-3073
//replace treechop:chopped_log minecraft:oak_log

However, it would be better if the old blocks wouldn't cause a crash with the new version.

**Comment by hammertater** [comment]
Sorry about that, the root of the crash should be fixed in 0.17.4. Hopefully there aren't any downstream crashes that didn't appear in the log. Old chopped blocks might look kinda funky but hopefully they function correctly.
