### ISSUE TITLE
Textures appear black when Smooth Lighting is off

### ISSUE THREAD

**Issue by StockiesLad** [hammertater/treechop#167]
![image](https://user-images.githubusercontent.com/60066663/218022450-bc10196f-04fa-4ddc-aa82-9d79fd93b912.png)

It isn't sodium or any other mod bc I tested just by itself.

**Comment by hammertater** [comment]
Thanks for reporting, I honestly have never tested with smooth lighting off. I’ll get it fixed 👍

**Comment by FluffyBumblebees** [comment]
I use smooth lighting because of the nostalgia aspect to it. Feels like beta days with it off.

**Comment by hammertater** [comment]
Well I'd hate to ruin the nostalgia - it's fixed in 0.17.3 (only on 1.19.2 at the moment)
