### ISSUE TITLE
Unable to add branch and log slabs to config

### ISSUE THREAD

**Issue by megaratboy96** [hammertater/treechop#169]
Hi, I want to add compatibility for the Lord of the Rings mod for 1.16.5. I added the tags under logs_whitelisted and the game crashes when loading up. How can I add tags or the branch name lotr:oak_branch?

	#The tag that blocks must have to be considered choppable (default: treechop:choppables)
	blockTagForDetectingLogs = "treechop:choppables", "lotr:log_slabs"
	#The tag that blocks must have to be considered leaves (default: treechop:leaves_like)
	blockTagForDetectingLeaves = "treechop:leaves_like"

**Comment by hammertater** [comment]
TreeChop for 1.16.5 only allows one block tag to be specified in the config. So, you’d need to make a datapack to add blocks to the `treechop:choppables` tag, or better yet, `minecraft:logs_that_burn`, which is included in the treechop tag

If you don’t wanna make a datapack, there might be a mod out there to help with fixing block tag issues. I believe there’s one for Fabric, not sure about Forge.

Either way, the best fix would be to ask the LotR mod devs to give their log and leaves blocks the appropriate block tags

**Comment by hammertater** [comment]
Closing, feel free to reopen if you're still having issues
