### ISSUE TITLE
Tesselating Block Model bug

### ISSUE THREAD

**Issue by Xerses707** [hammertater/treechop#170]
The game crashes upon trying to use optifine shaders and having a tree that is partially broken.

How to replicate -

1. Download optifine, Sildur's Basic Shaders Fancy, and HT Tree chop

2. Break a tree block with the shaders enabled.

3. Crash

I've attached the crash log.

Thank you for making an amazing mod btw :)

[crash-2023-02-20_09.56.18-client.txt](https://github.com/hammertater/treechop/files/10785990/crash-2023-02-20_09.56.18-client.txt)

**Comment by hammertater** [comment]
Thanks for reporting, I’ll get it fixed 👍

**Comment by Xerses707** [comment]
And thank you for being a wonderful mod author :)

**Comment by hammertater** [comment]
This might be fixed in 0.17.6. I only tested with SEUS shaders and it seemed to work. Let me know if you still get crashes?

**Comment by hammertater** [comment]
Just tested it with Sildur's shaders, all good!
