### ISSUE TITLE
Crash in Nether

### ISSUE THREAD

**Issue by Zarepheth** [hammertater/treechop#177]
My world crashes on load. Before it crashed on load it crashed when chopping a the trunk of a warped nether wart tree - at least I think it was the tree-like mushroom present in vanilla Minecraft. Unfortunately, the game crashes on joining the world, so I can't get the block info from Jade to verify.

I believe this is a rendering error, something going wrong with the partially chopped model.

Initial Crash Report: [crash-2023-02-25_19.57.58-client.txt](https://github.com/hammertater/treechop/files/10832757/crash-2023-02-25_19.57.58-client.txt)
World Load Crash Report: [crash-2023-02-25_20.07.03-client.txt](https://github.com/hammertater/treechop/files/10832758/crash-2023-02-25_20.07.03-client.txt)

Log for World Load Crash: [latest.log](https://github.com/hammertater/treechop/files/10832762/latest.log)

**Comment by hammertater** [comment]
Hey, sorry about the crashes. It's a conflict with the latest version of the Fabric API. It's fixed in https://github.com/hammertater/treechop/releases/tag/0.17.5

I'll post it to CurseForge soon

**Comment by Zarepheth** [comment]
I was chopping a "Warped Stem" block, from vanilla Minecraft, at the time of the crash. I was in "Old Warped Woods" biome, probably from one of the biome mods (I doubt the biome is vanilla). The Warped Stem was part of a 2x2 trunk for the large, warped, nether wart mushroom.

Turning off  HT's TreeChop got me reloaded, with the partially chopped block removed.

**Comment by Zarepheth** [comment]
I look forward to trying out the fix.

**Comment by hammertater** [comment]
Ok, version 0.17.6 is posted to CurseForge. I'm gonna close, but please do let me know if there are any further issues.
