### ISSUE TITLE
`NoClassDefFoundError: ht/treechop/common/chop/ChopUtil`

### ISSUE THREAD

**Issue by SettingDust** [hammertater/treechop#183]
```
class ht.treechop.plugin.wthit.TreeChopWthitPlugin
java.lang.NoClassDefFoundError: ht/treechop/common/chop/ChopUtil
	at TRANSFORMER/treechopwthit@0.1.1/ht.treechop.plugin.wthit.TreeChopWthitPlugin.appendBody(TreeChopWthitPlugin.java:52)
```

**Comment by hammertater** [comment]
Hey, thanks for reporting. Which version of TreeChop were you using? I believe this is fixed in the latest version but I could be wrong.

**Comment by SettingDust** [comment]
HT's TreeChop-0.16.3

**Comment by hammertater** [comment]
If you can, updating to TreeChop-0.17.8a will fix this. Otherwise, downgrade the WTHIT plugin to 0.1.0. To clarify,
* TreeChop WTHIT 0.1.0 works for TreeChop-0.16.x
* TreeChop WTHIT 0.1.1 works for TreeChop-0.17.x

Hope this helps!

**Comment by SettingDust** [comment]
It's fine. I'm using pmmo3 that supported by 0.16. So I using 0.1.0 and 0.16.3
