### ISSUE TITLE
HT's TreeChop Mod doesnt work

### ISSUE THREAD

**Issue by Mosby17** [hammertater/treechop#189]
Hello i need help my minecraft doesnt want to start up with HT's TreeChop Mod when i delete it its okey but when i put it back it just doesnt work and this is the error that pops out
![Snímek obrazovky 2023-04-10 192307](https://user-images.githubusercontent.com/130393092/230956047-6751691a-73a1-44a2-8359-aa778a8012eb.png)

**Comment by hammertater** [comment]
What versions of the mods are you using (can you give me their file names)? If you're not using the latest versions, updating one or both mods should fix it

**Comment by Mosby17** [comment]
TreeChop-forge-1.18.2-0.17.7

**Comment by hammertater** [comment]
That should work with [pmmo-1.18.2-6.0.2](https://www.curseforge.com/minecraft/mc-mods/project-mmo/files/4401568) and later. If you can't update PMMO, you could downgrade TreeChop to 0.17.2, but it's not as stable as the latest version

**Comment by hammertater** [comment]
Or you can always use the TreeChop config to disable PMMO support

**Comment by Mosby17** [comment]
well mc works but i have this problem now 
![Snímek obrazovky 2023-04-10 201619](https://user-images.githubusercontent.com/130393092/230965782-aedcbb4d-3a9e-4bd2-a41f-d64e7d75455b.png)

**Comment by Mosby17** [comment]
i just cant make it work, i made a server on Aternos and installed this modpack CurseForge DawnCraft - An Adventure RPG Modpack then downloaded it and added all the mods into my client but now this is popping out now 
![Snímek obrazovky 2023-04-10 201619](https://user-images.githubusercontent.com/130393092/230966929-c7dbab63-b8eb-4df2-ae08-40e3976f403b.png)

**Comment by hammertater** [comment]
Ah, you'd have to update the mods on the server too. Since the modpack includes both PMMO and TreeChop, your best bet might be to see if you can update the whole modpack, since it's a startup crash I assume they'd fix it

**Comment by hammertater** [comment]
Since this is just a version mismatch, I'm gonna close, but feel free to reopen if you're still having issues.
