### ISSUE TITLE
Chop Texture Bugs With Moded Woods

### ISSUE THREAD

**Issue by Blunder-G** [hammertater/treechop#194]
Oak texture is always displayed on the first break in modded trees. Fixes on the second break. I know it isn't clear so i took some screenshots:

**FIRST BREAK WITH AXE (QUARK'S BLOSSOM WOOD)**

![2023-04-30_21 53 28](https://user-images.githubusercontent.com/56030297/235372768-2df8e011-cdd6-4530-bb94-e439c99e8bf1.png)

SECOND BREAK WITH AXE

![2023-04-30_21 53 35](https://user-images.githubusercontent.com/56030297/235372790-6cceafa7-66ec-45e7-a5d3-5bc25e024673.png)

**Comment by hammertater** [comment]
Hey Blunder, thanks for reporting. Yeah, it's ugly. I'll be sure to get it fixed. Related to #157

**Comment by hammertater** [comment]
Fixed in TreeChop 0.18+ versions, currently only for Minecraft 1.19.4+
