### ISSUE TITLE
Totally incorrect work with BOP mystic big tree

### ISSUE THREAD

**Issue by KostromDan** [hammertater/treechop#195]
https://youtu.be/8Cq5iHYqLDQ
1. after destroying 4 first layers counter stops, we can break unlimited number of blocks but tree will never harvest.
2. If we continue break upper layer, counter displyes incorrect value.
3. After havesting  not all blocks of tree harvested.

**Comment by hammertater** [comment]
Hey Dan, thanks for reporting. Right now, only chopped blocks that are within a certain distance of each other get counted together, so really skinny trees that are really big are problematic. I'll be sure to fix this.

As an awkward temporary workaround, you could make the tree "fatter" by adding a couple more log blocks to its base. Each extra block should allow 7 more chops, I believe.

**Comment by hammertater** [comment]
Ok, it's fixed in 0.17.9, only for minecraft 1.19.3 at the moment. 1.19.4 and 1.18.2 will follow shortly.
