### ISSUE TITLE
TreeChop works in creative, but will revert back to vanilla chopping in survival.

### ISSUE THREAD

**Issue by hhut100** [hammertater/treechop#196]
I have tried changing all the configs and can't seem to find a fix, I can send my modlist if it helps, however it is extensive.

**Comment by hammertater** [comment]
Hey, sorry about that. Some questions:
- What minecraft and treechop versions are you using?
- Have you tried respawning?
- Are you playing on a server?
- If not on a server, have you tried deleting treechop-common.toml?

One of your log files should show your mod list, I don’t remember which one though. If you can find one, just upload the file

**Comment by hhut100** [comment]
Found out it was an incompatibility with MultiMine.

**Comment by hammertater** [comment]
Ah yeah, that’ll do it. Adding log blocks (or just `treechop:choppables`) to multimine’s blacklist should fix it.

**Comment by hammertater** [comment]
Closing as duplicate of #106
