### ISSUE TITLE
When is the release for 1.19.4? 

### ISSUE THREAD

**Issue by Jewrey** [hammertater/treechop#199]

**Comment by hammertater** [comment]
Tomorrow

**Comment by Jewrey** [comment]
Ok :3

**Comment by hammertater** [comment]
Well, 1.19.3 is up. 1.19.4 will follow tomorrow, for real this time

**Comment by NeverGio** [comment]
releasing sometime today?

**Comment by hammertater** [comment]
It'll be posted to CurseForge in a few minutes. I didn't do much testing, so please let me know if you run into any (new) bugs.
