### ISSUE TITLE
Crash on Minecraft 1.19.4 with Quilt

### ISSUE THREAD

**Issue by ParodyVerse** [hammertater/treechop#204]
[crash-2023-06-25_17.09.41-client.txt](https://github.com/hammertater/treechop/files/11861211/crash-2023-06-25_17.09.41-client.txt)
When I click any button Minecraft crashes when I have your mod. (Crash log above)
Minecraft 1.19.4
Quilt 0.19.1
Treechop 0.17.9

**Comment by hammertater** [comment]
Thanks for reporting, I'll get it fixed

**Comment by ParodyVerse** [comment]
It's also a bug on coordinates display and picohud so I'll have to report it there too and i've reported it on Quilt's github

**Comment by hammertater** [comment]
Ah, it may be something else then, or an issue with Quilt's Fabric compatibility. I just tried with Minecraft 1.19.4, Quilt 0.19.1, and only Treechop 0.17.9, and it seems to work for me.

Note to self - quilt issue is https://github.com/QuiltMC/quilted-fabric-api/issues/106#issue-1773565815

**Comment by ParodyVerse** [comment]
![mods](https://github.com/hammertater/treechop/assets/32398836/e2d589de-3e48-4cd3-9f26-95451f5a251c)
Do you think any of my mods could be the issue?

**Comment by ParodyVerse** [comment]
Turns out it was a bug with Yet Another Config Library.

**Comment by ParodyVerse** [comment]
The dev of picoHUB noticed it :D

**Comment by hammertater** [comment]
Oh good! Glad it's sorted out and I don't have to fix anything 😃 Closing!
