### ISSUE TITLE
Player Missing Chop Settings

### ISSUE THREAD

**Issue by PhunghisKhan** [hammertater/treechop#206]
I'm noticing this error/warn message that pops up when a player respawns after a death.

> [treechop/]: Player ServerPlayer['__User__'/35603, l='ServerLevel[world]', x=-1470.89, y=13.00, z=-765.30, removed=KILLED] is missing chop settings

_I replaced the username and world for privacy_

This warning always pops up AFTER a player clicks respawn.

I have a few mods on here but the ones that affect dying and respawning is PlayerRevive, I also have keepInventory after death set to true.

I saw on issue opened about this but never resolved, I apologize if this has already been dealt with.

Thanks in advance!

**EDIT**
Also wanted to add that this hasn't effected anything else in terms of mechanics or gameplay. It is an error that I just wanted to check to see if it can be explained. **All players can still access the treechop menu.**

**Comment by hammertater** [comment]
Hey, thanks for reporting. What versions of Minecraft & TreeChop is this happening on?

**Comment by PhunghisKhan** [comment]
Thanks for looking into this!

It's a 1.19.2 MC server, version of HT Tree chop is... 

TreeChop-1.19.2-forge-0.17.8a.jar

**Comment by hammertater** [comment]
Sorry, it's been fixed in 1.19.4+ but not yet for 1.19.2. It'll come

> Also wanted to add that this hasn't effected anything else in terms of mechanics or gameplay. It is an error that I just wanted to check to see if it can be explained. All players can still access the treechop menu.

Thanks for sharing - it's possible that player chop settings are getting reset on death, but I think that's the worst that could happen

**Comment by hammertater** [comment]
Fixed in 1.19.2 as of treechop 1.18.3
