### ISSUE TITLE
Chopping doesn't work

### ISSUE THREAD

**Issue by kryakovsky** [hammertater/treechop#209]
Mod works in single, but when installed on server, blocks are destroyed in usual way, only leaves break as should. Console writes: 
> Player ServerPlayer['Lic'/1733, l='ServerLevel[world]', x=621.43, y=70.75, z=1181.00, removed=KILLED](Lic at 621.4319404194615,70.7531999805212,1180.9950684973896) is missing TreeChop data

Minecraft version: 1.19.4
Forge version: 45.1.2

**Comment by kryakovsky** [comment]
The server started to crash when chopping the top of the tree.
I need to say, that we changed server to 1.19.2 with forge core instead of 1.19.4 mohist. Maybe that was the core problem, not mod really. Anyway old server closed now, so i can't say more about mod updates.
But thank you for update and help anyway.

**Comment by hammertater** [comment]
Ahhh yeah, those fancy servers sometimes mess with some Forge features that TreeChop uses. Either way, I reworked things and that "missing TreeChop data" error case no longer exists, so the mod should be more stable going forward.
