### ISSUE TITLE
Server Crashing On Final Chop

### ISSUE THREAD

**Issue by bolemangaming** [hammertater/treechop#210]
This mod alone is causing my server to crash on the final stage of the chopping after completion. 
Works in single player mode though.

Server Setup
i7-7700k CPU
25gb Ram
1.20.1 Fabric

**Comment by hammertater** [comment]
Sorry about that. Could you share a crash log?

**Comment by halbirdd** [comment]
I'm having the same issue, granted, my server is running approx 74 mods. This is my first time reporting a crash, so unsure of what crash log files are needed. Attached is the file that seems the most relevant.
[crash-2023-07-22_18.29.47-server.txt](https://github.com/hammertater/treechop/files/12137356/crash-2023-07-22_18.29.47-server.txt)

**Comment by hammertater** [comment]
Hey, thanks for the log! I see the error, I'll get it fixed right away

**Comment by hammertater** [comment]
I've posted a new 1.20.1 version (0.18.1) on CurseForge, it should be available in a few minutes. 1.19.4 will follow

**Comment by halbirdd** [comment]
Appreciate the prompt response!

**Comment by bolemangaming** [comment]
Appreciate the fix! The Fabric version is working very well with my other 27 mods.

Listed below to show you the compatibility!

1. Immersive Portals
2. Visual Overhaul
3. Diagonal Fences 
4. Connectible Chains
5. Visual Workbench
6. Universal Bone Meal
7. Not enough animations
8. Interactic
9. Falling leaves (particle effect)
10. Enchantment Descriptions
11. Apple Skin
12. Zoomify
13. ShowMeWhatYouGot
14. River Redux
15. Rare Ice
16. Horse Stats
17. Geophilic
18. Furnace Recycle
19. Friends and Foes
20. Feeding Trough
21. Easy Shulker Box
22. Easy Magic
23. Easy Anvils
24. Creeper Overhaul
25. Crafting UI Tweaks
26. Chunky
27. Axes Are Weapons
28. Amplified nether

**Comment by hammertater** [comment]
Nice, thanks! I'm always on the lookout for adding compatibility with other mods, so do let me know if you have any requests :)
