### ISSUE TITLE
[Question] What is the texture path of your mod?

### ISSUE THREAD

**Issue by IntM4rco** [hammertater/treechop#213]
I am using this the Mindful Darkness mod which consists of an algorithm that darkens every aspect of the GUI. However I don't want your textures to be darkened so I have to put the path to each texture in the configuration. Could you tell me the one in your mod please.

This is an example of another mod: !dynamiccrosshair:textures/gui/crosshairs.png

What I would like to keep unchanged is this: (The axe icon)
![Screenshot 2023-08-14 alle 18 06 35](https://github.com/hammertater/treechop/assets/124934175/3babc931-7d76-4390-b7bf-b35179d66a12)

**Comment by hammertater** [comment]
All of treechop's GUI icons are in the same texture file, `treechop:textures/gui/widgets.png`. I hope it works!

**Comment by IntM4rco** [comment]
Ty so much.
