### ISSUE TITLE
Latest Update break vein- and AoE-mining

### ISSUE THREAD

**Issue by KatoNamus** [hammertater/treechop#214]
Hi, TreeChop-1.19.2-forge-0.18.3.jar breaks PMMO's vein mining and Silent Gear's AoE hammer mining.

**Comment by hammertater** [comment]
Hey, thanks for reporting! It might be because of the Multi Mine compatibility, you can turn that off in config/treechop-common.toml. I'll get it fixed

**Comment by qwltech** [comment]
Hi, also observed this with Botania. My terrasteel shatterer can't mine 5x5 anymore. I hear the 25 blocks breaking and see the corresponding particle effects of 25 blocks breaking, but only the block under the cursor breaks. Downgraded to previous version for now. I love Treechop.

**Comment by aNinjin** [comment]
Hello, I wanted to chime in here to add to this. I was trouble shooting and found out that what ever happened from 0.18.2 to 0.18.3 broke all aoe mining affects. With 0.18.2, aoe mining works perfectly.

This happens with many mods I've tried. I've tried multiple mods to make sure it wasn't just a one off incompatibility.
Mods I tested:
Vanilla Plus Tools
Simply Tools
The Hammer Tools Extensions and More

**Comment by hammertater** [comment]
Thanks for the info! After some digging, I'm back to thinking the Multi Mine compat is the issue. Have you tried disabling it in treechop-common.toml?

I'll try to fix this tonight, but no promises

**Comment by KatoNamus** [comment]
> Thanks for the info! After some digging, I'm back to thinking the Multi Mine compat is the issue. Have you tried disabling it in treechop-common.toml?
> 
> I'll try to fix this tonight, but no promises

Sorry, it still doesn't work after disabling MultiMine compat.

Updated to 0.18.3, launched, disabled MultiMine compat, opened world, tested PMMO vein mining (vanilla tool, still only breaks a single block), tested Silent Gear hammer (still only breaks a single block).

**Comment by KatoNamus** [comment]
Had a chance to test the update and it works fine. I do get an some kind of error in the Jade tooltip when I chop down trees though (Silent Gear and Malum's trees specifically, didn't try vanilla trees). I can't recall what it says ad verbatim, but it's something along the lines of "error occurred, report to mod author".
I can post logs a bit later if you'd like.

**Comment by peacegangsta** [comment]
I have the same issue of excavar not working with the forge version in 1.20.1

**Comment by P3rf3ctXZer0** [comment]
I wish I suspected this sooner I spent 3 days to come a to a conclusion yall had weeks ago.

**Comment by hammertater** [comment]
Fixed in 0.18.7, sorry for the wait!
