### ISSUE TITLE
SimplyTools compat

### ISSUE THREAD

**Issue by MelanX** [hammertater/treechop#217]
I got this issue: https://github.com/MelanX/SimplyTools/issues/9
As mentioned in this issue, the problem is caused by HT's TreeChop. This happens because the `BreakEvent` gets canceled because of this `PreChopEvent` cancelation: https://github.com/hammertater/treechop/blob/28f8ab3c9b62ad4e14b77d1e92e0245914177af6/forge/src/main/java/ht/treechop/compat/MultiMine.java#L34

This results in only breaking one block when breaking. Here you can see my implementation for breaking more than one block: https://github.com/MelanX/SimplyTools/blob/15225940638c03503fb1476294d5eeae53b68ba5/src/main/java/de/melanx/simplytools/util/BlockBreaker.java#L23-L38

**Comment by MelanX** [comment]
Probably related to #214

**Comment by hammertater** [comment]
This should be fixed in 0.18.4, but I'll leave this issue open til I can confirm
