### ISSUE TITLE
Excavar compat

### ISSUE THREAD

**Issue by MelanX** [hammertater/treechop#218]
Similar to #217.
My implementation: https://github.com/MelanX/Excavar/blob/1528a5988741b1bd382c1a09f4c5314ea0cbfa26/src/main/java/de/melanx/excavar/api/Excavador.java#L132-L145

Setting multiMine config to false fixes the problem, too.

**Comment by MelanX** [comment]
Probably related to #214

**Comment by hammertater** [comment]
This should be fixed in version 0.18.4. Sorry about that!

**Comment by hammertater** [comment]
Note that Excavar and TreeChop do not work well together when breaking trees, but I'm not too concerned -- it doesn't really make sense to use them together. As long as TreeChop doesn't break Excavar, I'm happy.
