### ISSUE TITLE
I was told to report!

### ISSUE THREAD

**Issue by RubySushi** [hammertater/treechop#226]
Hello! Was just playing around and got a jade item description something along the lines of "HT Tree chop error, plz report" so here it is! I am using the mod with the pyromancer mod which in addition to other things adds two trees to the nether.

![2023-09-12_17 25 54](https://github.com/hammertater/treechop/assets/131213396/0662a96a-47b4-478f-8881-13811405a6c4)

![2023-09-12_17 25 47](https://github.com/hammertater/treechop/assets/131213396/795b5d85-7324-458a-b27f-a3fe07144fca)

**Comment by hammertater** [comment]
Hey, sorry about that. This is the same as #200, so I'm gonna close this and keep that issue open
