### ISSUE TITLE
Tree Chop version 0.18.3 breaks FTB Ultimine. Possibly others

### ISSUE THREAD

**Issue by redwolf41** [hammertater/treechop#227]
Hi, so I was playing a modpack called Prominence 2, a 1.20 pack. I wanted to add vein mining. I tried a few different mods that all do the same thing, but they all had the same issue. The last one I was trying was FTB Ultimine and I was able to figure out that the issue is some kind of conflict with Tree Chop. When I have Tree Chop in the pack, the vein mining mod "activates" but only mines one block instead of the whole group. I havent tested the other vein mining mods I'd tried since Ultimine is working and I'd rather stick with that, but I'll list out the other mods I tried below. I can provide any other information necessary if you need it. I just wanted to met you know this was an issue (or an ongoing issue if it was reported on a previous version).

Mod Loader: Forge
Minecraft Version: 1.20.1
Tree Chop Version: 0.18.3

Mods tested/tried: 
Vein Mining
Excavar
Simple Vein Mining
FTB Ultimine

**Comment by hammertater** [comment]
Same as #214

**Comment by hammertater** [comment]
Fixed in 0.18.7, sorry for the wait!
