### ISSUE TITLE
[1.20.1] [Fabric] Game not launching without forgeconfigapiport

### ISSUE THREAD

**Issue by sirben99** [hammertater/treechop#230]
Hey!

It seems that the latest version of Treechop requires forgeconfigapiport as an dependency, but its not mentioned at curseforge at all. 
I assume the mod requires this mod as an libary: https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric

Is this a error or just an oversight?

Minecraft version: Fabric
Fabric loader: 0.14.23
Fabric API: 0.90.0
TreeChop: 0.18.3

Log: https://pastebin.com/LFP5Xv7N

**Comment by hammertater** [comment]
Ahh, thanks for reporting - I did some cleaning up on the mod page and accidentally removed the bit about the dependency. Yes, forgeconfigapiport is required for the Fabric versions. I'll be sure to document this
