### ISSUE TITLE
Сompatible Apotheosis

### ISSUE THREAD

**Issue by Willem07** [hammertater/treechop#231]
Is it possible to be compatible with the Chainsaw Enchantment from the Apotheosis mod?

[TreeChop-1.20.1-forge-0.18.3](https://legacy.curseforge.com/minecraft/mc-mods/treechop/files/4685647)
[Apotheosis-1.20.1-7.0.5](https://legacy.curseforge.com/minecraft/mc-mods/apotheosis/files/4724390)

_or is the compatibility problem on the side of the developers of the Apotheosis mod?_

**Comment by Willem07** [comment]
Also take a look at this error
[#269](https://github.com/embeddedt/ModernFix/issues/269)

**Comment by hammertater** [comment]
Not sure, I'll look into it and try to add compatibility if I can

**Comment by hammertater** [comment]
Added in 0.18.7, sorry for the wait!
