### ISSUE TITLE
Mod not working with "Vein mining" Mod

### ISSUE THREAD

**Issue by TheaRTGGaming** [hammertater/treechop#238]
when i have the Vein Mining enchantment on my tools it does not activate when i use it. with your mod installed

[Vein Mining (Fabric/forge/Quilt](https://www.curseforge.com/minecraft/mc-mods/vein-mining)

**Comment by hammertater** [comment]
Sorry for the late reply. I'll get it fixed. I assume you're on 1.20.1?

**Comment by TheaRTGGaming** [comment]
yes

**Comment by joveice** [comment]
What is the status on this one?
Also does not look like it's related to the enchantment, but that mod in general. I tried the without enchantment config and that doesn't work as well.

**Comment by hammertater** [comment]
This should be fixed in 0.18.7, sorry for the wait!

**Comment by joveice** [comment]
Works like a charm! Tested on the none-enchanted version in Vein mining. Thank you for fixing!
