### ISSUE TITLE
Causes mod "Bag of Yurting" to act unpredictably with default settings

### ISSUE THREAD

**Issue by RiscmonIngk** [hammertater/treechop#239]
HT Treechop causes BOY to act unpredictably, though after tweaking configurations in HTTC, it seems to work. unfortunately i have no idea what i did.

**Comment by hammertater** [comment]
Sorry for the late reply! I'm guessing you disabled the MultiMine compatibility - that was the root of the issue. It'll be fixed in the next version, assuming you're on 1.20.1

**Comment by hammertater** [comment]
Fixed in 0.18.7, sorry for the wait!
