### ISSUE TITLE
Error displaying chop count in jade (minecraft 1.19.2)

### ISSUE THREAD

**Issue by 905Sunny** [hammertater/treechop#241]
When I start chopping the tree, the counter is shown as screenshot below

![2023-11-11_18 27 12](https://github.com/hammertater/treechop/assets/44795811/1a30c692-6fe5-410d-b76e-0b6d275cae9b)

Here is the jade error output that showed the error in jade

[JadeErrorOutput.txt](https://github.com/hammertater/treechop/files/13325211/JadeErrorOutput.txt)

**Comment by hammertater** [comment]
Thanks, it'll be fixed in the next version

**Comment by hammertater** [comment]
Fixed in 0.18.5
