### ISSUE TITLE
[Incompatibility] Regions Unexplored brimwood_leaves

### ISSUE THREAD

**Issue by KostromDan** [hammertater/treechop#242]
Incompatibility with new biome(regions_unexplored:infernal_holt) trees from lastest Regions Unexplored major update.
Decpite the fact that they have '#minecraft:leaves' tag.
I've tried to add leaves to:
![image](https://github.com/hammertater/treechop/assets/90044015/f311c61c-2048-4d48-95ef-aa4a743a7405)
but doesn't helped.
Replacing this leaves to any other fixes problem, so problem not with logs.
![image](https://github.com/hammertater/treechop/assets/90044015/2bc529a1-dd82-4d55-8989-5764e7760ee7)

**Comment by hammertater** [comment]
Thanks for reporting. Usually this is because the leaves are marked "persistent". Not sure what Minecraft version you're on, but in treechop 0.18.4 (only for 1.19.2 at the moment) you can add these kinds of misbehaving blocks to the lists in `compatibility.trees.problematicLeavesTrees` in treechop-common.toml and treechop will make sure to break them

**Comment by KostromDan** [comment]
> Thanks for reporting. Usually this is because the leaves are marked "persistent". Not sure what Minecraft version you're on, but in treechop 0.18.4 (only for 1.19.2 at the moment) you can add these kinds of misbehaving blocks to the lists in `compatibility.trees.problematicLeavesTrees` in treechop-common.toml and treechop will make sure to break them

TreeChop-1.19.2-forge-0.18.4.jar
Doesn't help.
tried:
"regions_unexplored:.*_leaves"
"regions_unexplored:brimwood_leaves"
![image](https://github.com/hammertater/treechop/assets/90044015/f288118b-ee1a-4bac-8552-902322f9b4ed)

**Comment by KostromDan** [comment]
Maybe related with this.
https://github.com/UHQ-GAMES-MODS/REGIONS_UNEXPLORED_FORGE/issues/68

**Comment by KostromDan** [comment]
Also just noticed incorrect processing of redwood trees from this mod.
![image](https://github.com/hammertater/treechop/assets/90044015/92d46d06-0544-4e6c-91f0-d1d07b9f8c05)

**Comment by hammertater** [comment]
> > Thanks for reporting. Usually this is because the leaves are marked "persistent". Not sure what Minecraft version you're on, but in treechop 0.18.4 (only for 1.19.2 at the moment) you can add these kinds of misbehaving blocks to the lists in `compatibility.trees.problematicLeavesTrees` in treechop-common.toml and treechop will make sure to break them
> 
> TreeChop-1.19.2-forge-0.18.4.jar Doesn't help. tried: "regions_unexplored:.*_leaves" "regions_unexplored:brimwood_leaves" ![image](https://private-user-images.githubusercontent.com/90044015/282938922-f288118b-ee1a-4bac-8552-902322f9b4ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4MjgzNDYsIm5iZiI6MTcwMTgyODA0NiwicGF0aCI6Ii85MDA0NDAxNS8yODI5Mzg5MjItZjI4ODExOGItZWUxYS00YmFjLTg1NTItOTAyMzIyZjliNGVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDAyMDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljNzk1MjdhMTdlOTFlMjc1OTE2ZDExMjk0M2Q3ZGI2MTZiODk2NDJiYzgxNzg5MGI1OTc4YzYzMzNlNGI2MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VQHKx0LyN8CLGGdpBJeOYf_PMLAG8s2QYdAoUMgOSRY)

Ah, you did it right, but I forgot to actually ignore persistence for "problematic leaves". Sorry about that! It's fixed in 0.18.5, fresh out of the oven.

> Also just noticed incorrect processing of redwood trees from this mod.

Thanks for the screenshots! I've added redwoods to the list at https://github.com/hammertater/treechop/issues/44, and I'll close this issue since it's for the brimwoods
