### ISSUE TITLE
Client crash when playing on a server (1.20.1)

### ISSUE THREAD

**Issue by SeagalKru** [hammertater/treechop#251]
Hello!
I played for some time without problems on my server with your mod.
Today, near my house (in the game, of course) I made a 2x2 dirt plot in the sand, on which I planted 4 oak sprouts.
After all 4 sprouts had grown, I decided to cut it down with a diamond axe.
At this moment the game crashed (only the client, the server continued to work).
I am attaching the crash log files and the log file.
Hope this helps find and fix the problem.
Thank you!
[crash-2024-01-13_21.09.08-client.txt](https://github.com/hammertater/treechop/files/13929102/crash-2024-01-13_21.09.08-client.txt)
[latest.log](https://github.com/hammertater/treechop/files/13929103/latest.log)

**Comment by hammertater** [comment]
Thanks for the logs! I'll get it fixed asap

**Comment by hammertater** [comment]
Fixed in 0.18.7a

**Comment by SeagalKru** [comment]
Please forgive me, but I have the same problem, but with seedlings of a different tree (dark oak).
I'm starting to get the impression that this might be the case with a few more tree species.
Now it’s already night for me, so I’ll better go to bed, and tomorrow I’ll wake up and try all the trees that are in my assembly.
And then I’ll additionally upload more log files.
Apparently, it is too early to close this topic.
Sorry again.
[crash-2024-01-14_03.51.00-client.txt](https://github.com/hammertater/treechop/files/13929953/crash-2024-01-14_03.51.00-client.txt)
[latest.log](https://github.com/hammertater/treechop/files/13929955/latest.log)

**Comment by hammertater** [comment]
Hey, thanks for letting me know. It was a conflict with some Flywheel optimizations, it should be fixed for real this time in 0.18.7b

**Comment by SeagalKru** [comment]
I updated the mod, went to the server and continued cutting down the dark tree. Made 4 hits, maybe 5 and crashed again. I am attaching the files. The thought flashed through that perhaps it was due to the fact that the earth blocks were installed in a sand block. It’s just that if I cut down trees at the place of their natural generation (when they grow during the generation of the world, and not the seedlings I planted), then no problems occur. all the trees are cut down (also dark wood or db, for example: I have cut them down more than once).
I found a problem for you! :-)
Sorry!
[crash-2024-01-14_14.27.38-client.txt](https://github.com/hammertater/treechop/files/13931246/crash-2024-01-14_14.27.38-client.txt)
[latest.log](https://github.com/hammertater/treechop/files/13931247/latest.log)

**Comment by hammertater** [comment]
Uh oh! The log says you’re still using TreeChop-1.20.1-forge-0.18.7.jar, could you update to TreeChop-1.20.1-forge-0.18.7b.jar? Note the “b” at the end

The server doesnt crash because it’s happening in code that draws stuff on your screen, and servers don’t have to do that

Thanks for always sharing logs :)

**Comment by SeagalKru** [comment]
Tricky Minecraft! ;-)
I was very surprised that I was using an old version of the mod, although I was updating it.
I decided to go into the “mods” folder and saw that both the old and new versions of mods “live together” in it! ;-)
And Minecraft itself did not report that it has duplicate mods (or several identical mods).
I deleted the old version, leaving the new one.
I went into the game, onto the server. I cut down a tree, planted new seedlings: I’m waiting for it to grow!
I'll report the results anyway!
We are waiting! )

**Comment by SeagalKru** [comment]
Hah!
While I was writing this message to you, the tree grew!
Well, I cut it down without any problems! So far everything is working!
I think this topic can be closed.
If I discover anything again, I will definitely let you know.
It was a pleasure to be useful and help you find and fix the problem with your mod!
Thank you for your mod: it’s very convenient to survive in this wonderful world of Minecraft!
;-)
