### ISSUE TITLE
0.18.7x does not like Flywheel's optimizations - render crash, 1.20.1 forge

### ISSUE THREAD

**Issue by MrGraphic** [hammertater/treechop#255]
Just Create and TreeChop.
No crashes after switching optimizations off.
https://gist.github.com/MrGraphic/ce52cd2f6d85a842b9c909d58118625a

**Comment by hammertater** [comment]
Welp. That's unfortunate. I'll fix it asap, thanks for reporting

**Comment by hammertater** [comment]
Should be fixed in 0.18.7b

**Comment by MrGraphic** [comment]
Downloaded...tested and confirmed. 
Thank you very much!
Closing.

**Comment by hammertater** [comment]
Nice! Thanks for confirming 🥇
