### ISSUE TITLE
Chopped Logs don't render smaller

### ISSUE THREAD

**Issue by WenXin20** [hammertater/treechop#259]
Minecraft v1.20.1-forge
TreeChop v0.18.7b

After updating, the chopped logs don't render smaller past the first chop and still renders the overlay on chopped logs. The hitbox still becomes smaller, but visually appears the same.
![image](https://github.com/hammertater/treechop/assets/12000593/058abe13-56ac-441f-ae19-8089b6da9a20)

**Comment by PinkLasagna03** [comment]
I have the same issue

**Comment by PinkLasagna03** [comment]
> This issue seems to be present when Indium is installed with the latest update of TreeChop. Removing indium fixes this.

Nope, I have tested this with just TreeChop installed and I still have the issue.

**Comment by phosmiro** [comment]
You're right. I noticed that installing Sodium makes logs update properly. But after installing Indium with Sodium, it doesn't work again.

**Comment by hammertater** [comment]
Ahh shucks. Thanks for the info everyone. The way Forge, Sodium, and Indium (etc.) all mess with Minecraft's rendering process is not fun. I'll get it fixed

**Comment by WenXin20** [comment]
I am also using Embeddium on forge with my pack

**Comment by hammertater** [comment]
0.18.8 is posted. Things should work better now for Forge/Embeddium and Fabric/Sodium/Indium

**Comment by WenXin20** [comment]
I'll close this since this is fixed for me

**Comment by hammertater** [comment]
Wonderful :)
