### ISSUE TITLE
Add trees from another mod?

### ISSUE THREAD

**Issue by SugarDaddii** [hammertater/treechop#261]
Is it possible to add trees of a mod where it’s not possible to chop down trees?
The pine tree of meadow is not choppable and I want to add combat is that even possible or need the mod author add compatibility?

**Comment by hammertater** [comment]
Sorry for the late reply! Which versions of TreeChop and Meadow are you using? Looking at their source code, I can see they added treechop compatibility in the latest version (https://github.com/satisfyu/Meadow/commit/2190688dc2b2c74192565b5112196e8453957e26)

**Comment by SugarDaddii** [comment]
Iam using version for Minecraft 1.19.2. ATM iam using a datapack to add combat.
Have a nice day

**Comment by hammertater** [comment]
Sorry I disappeared - I see you fixed it in https://github.com/satisfyu/Let-s-Do-Hub/issues/8. Thanks for sharing that! Closing.
