### ISSUE TITLE
Treechop does not work in survival

### ISSUE THREAD

**Issue by AzuryxxVortex** [hammertater/treechop#266]
Hello- No clue what's causing this, surely an incompatibility but I don't quite know which..

[latest.log](https://github.com/hammertater/treechop/files/14111065/latest.log)

If I could get help I'd be very glad-

**Comment by hammertater** [comment]
Hi! Could you update to treechop 0.17.8? I’m not sure if it will fix it but there’s a good chance

**Comment by AzuryxxVortex** [comment]
> Hi! Could you update to treechop 0.17.8? I’m not sure if it will fix it but there’s a good chance

0.17.8 is only for 1.19.2 though? And I'm running version 0.18.8, latest on Modrinth at this time-
I could try to rollback.

**Comment by hammertater** [comment]
Sorry, I meant 0.18.8*, oops!

**Comment by hammertater** [comment]
> 0.17.8 is only for 1.19.2 though? And I'm running version 0.18.8, latest on Modrinth at this time-
I could try to rollback.

The log file showed you were using 0.18.7. Maybe you had both versions in your mods folder?

**Comment by AzuryxxVortex** [comment]
I checked, I didn't have duplicates..
But, all 0.18.7 to 0.18.8 (available versions) does not work in my modpack for some reason, only 0.18.3

**Comment by AzuryxxVortex** [comment]
Still a problem to this day, even on latest.. Unsure what's still causing it but, heck
Something in 0.18.7 must've broken-
[latest.log](https://github.com/hammertater/treechop/files/15144861/latest.log)

**Comment by Krampus69** [comment]
Same here! Works perfectly fine in creative though

**Comment by AzuryxxVortex** [comment]
Root cause found; Incompatibility with "MultiMine" as mentioned in #293
