### ISSUE TITLE
doesn't work with spectrum/revelationary

### ISSUE THREAD

**Issue by 800020h** [hammertater/treechop#268]
TreeChop-1.20.1-fabric-0.18.8
spectrum-1.7.6-deeper-down

expected:
you chop a coloured tree (after you have unlocked/revealed them) and get the coloured tree loot (logs and leaves)

happens:
you chop a coloured tree (after you have unlocked/revealed them) and get oak tree loot (logs and leaves)

oak tree loot is what you should get if you haven't unlockeded/relealed coloured trees yet

note:
1 coloured log dropped probably the one that was targeted

**Comment by hammertater** [comment]
Thanks for reporting, I'll look into it

**Comment by Slayer5934** [comment]
Same issue for 1.19.2 (if this is still being supported for that)

**Comment by hammertater** [comment]
Fixed in treechop 0.19.0, will port to minecraft 1.19.2

**Comment by Slayer5934** [comment]
> Fixed in treechop 0.19.0, will port to minecraft 1.19.2

Thank you, I appreciate you

**Comment by Slayer5934** [comment]
> Fixed in treechop 0.19.0, will port to minecraft 1.19.2

Any news? o:
