### ISSUE TITLE
Missing Texture (pink checker) particles with physics mod fracturing

### ISSUE THREAD

**Issue by Barerock** [hammertater/treechop#269]
The physics mod lacks a texture to apply to the chunks that come off of the chopped_log. Physics Type: Off in Block Settings > Customize > treechop:chopped_log fixes issue. Can't believe I didn't report this before, having done this fix several times now.

1.20.1 versions, but it's across 1.18.2 -> 1.20.1 at least.

**Comment by hammertater** [comment]
Thanks for reporting! I'll look into it

**Comment by hammertater** [comment]
Only happening on Forge, Fabric looks fine

**Comment by hammertater** [comment]
Fixed in 0.19.0
