### ISSUE TITLE
Bug with Majrusz's Enchantments

### ISSUE THREAD

**Issue by ChicknTurtle** [hammertater/treechop#270]
When using an axe (or any tool) enchanted with Telekinesis from Majrusz's Enchantments, you will be given a log from the tree when it hasn't been fully chopped. Using this you can get infinite logs without ever fully breaking the tree.

**Comment by hammertater** [comment]
Thanks for reporting! I'll look into it

**Comment by hammertater** [comment]
Should be fixed in 0.19.0 but I haven't tested it. Also in the new version, I think telekensis will grab all blocks from felled trees.

**Comment by ChicknTurtle** [comment]
I tested the new version, and the bug is fixed. Telekinesis doesn't collect all blocks, only the block that was broken.

**Comment by hammertater** [comment]
Ok, great! Thanks for confirming
