### ISSUE TITLE
Game doesn't load if Truly Modular is also installed

### ISSUE THREAD

**Issue by DaeTheDerg** [hammertater/treechop#273]
When [Truly Modular API](https://modrinth.com/mod/modular-item-api) is added alongside treechop, the game fails to load, & complains that the TreechopUtil API doesn't exist if I read this correctly

![Screenshot_20240321_141241](https://github.com/hammertater/treechop/assets/80906771/38305afd-1371-4302-a37e-3945c16549fb)

is this something fixable on your end? (creating issue here first as this mod is the one referenced in the error report)

**Comment by hammertater** [comment]
Thanks for reporting, could you send me your latest.log file for this error?

**Comment by DaeTheDragon** [comment]
> could you send me your latest.log file for this error?

Sure! Here you go-
[latest.log](https://github.com/hammertater/treechop/files/14724582/latest.log)

**Comment by hammertater** [comment]
Thanks! Looks like the crash is fixed in a new version of Truly Modular API, per https://github.com/Truly-Modular/Modular-Item-API/issues/33

**Comment by hammertater** [comment]
Haven't heard any further issues, so I assume this is fixed. Closing.
