### ISSUE TITLE
Update to 1.21.1? :D

### ISSUE THREAD

**Issue by LoganHall195** [hammertater/treechop#294]

**Comment by JustEcliipse** [comment]
hopefully soon

**Comment by hammertater** [comment]
Hey folks, I'm finishing up 1.21 support, I'll tackle 1.21.1 next.

**Comment by hammertater** [comment]
Actually, I'm not sure what the compatibility situation for 1.21.1 is. It's possible the 1.21 version works (only for Fabric currently).

**Comment by JustEcliipse** [comment]
yup, it works on 1.21.1

**Comment by JustEcliipse** [comment]
thank you for the update by the way!

**Comment by hammertater** [comment]
Nice! No problem :)
