### ISSUE TITLE
Cactus blocks are marked as "treechop:choppables"

### ISSUE THREAD

**Issue by clootas** [hammertater/treechop#30]

**Comment by clootas** [comment]
Structurize adds the "minecraft:logs" tag, ignore this. Fixed through KubeJS code:

`onEvent('block.tags', event => {
  event.remove('minecraft:logs', 'minecraft:cactus')
})`

**Comment by hammertater** [comment]
Sweet! Thanks for figuring out the cause of this and finding a fix. Structurize might have a good reason for adding the tag to cactus blocks, so maybe it would be better to remove 'minecraft:cactus' from 'treechop:choppables'? Assuming KubeJS (I haven't used it before) removes 'minecraft:cactus' after 'treechop:choppables' has been baked into the block tags.

**Comment by clootas** [comment]
I tried this and troubleshooted with the dev of KubeJS for like 30 minutes before realizing that this mod requires a block to be tagged with 'minecraft:logs' in order for it to be tagged with 'treechop:choppables'. I then learned that, like you said, KubeJS can't remove a tag if said tag depends on another tag. Cheers man, this is easily the best implementation of a tree chopping mod
