### ISSUE TITLE
Suggestion: "Inverse" mode where tree chopping only happens while sneaking (or other keybind)

### ISSUE THREAD

**Issue by egshels** [hammertater/treechop#33]
Basically the opposite of when sneaking does normal log breaking

**Comment by hammertater** [comment]
Hi Eggshells, that actually already exists, but it's not well-documente. Press `n` to turn chopping off (the key can be changed in Options > Controls). While it's off, sneaking will cause you to turn chopping on instead of off.

I should probably include this in a FAQ on the mod page.

**Comment by egshels** [comment]
I see. Thanks!
