### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [hammertater/treechop#36]
`Minecraft v1.16.5`
`Forge v36.0.1`
`Tree Chop v0.12.0`

My server crashed while loading the mod.
[Crash Report](https://gist.github.com/WenXin20/5d69ca49748eeb4800ad0c9e371407f9)

**Comment by hammertater** [comment]
Oof. I'll have it fixed right away.

**Comment by WenXin20** [comment]
Thanks!

**Comment by hammertater** [comment]
It's gonna take longer to fix than I'd hoped. I've taken version 0.12.0 down for now, but hopefully I'll have a fix out tomorrow. Sorry for the trouble!

**Comment by WenXin20** [comment]
Ah, no worries!

**Comment by hammertater** [comment]
It's fixed in 0.12.1. I'm gonna go ahead and close this issue. Thanks for reporting the crash so quickly!
