### ISSUE TITLE
Too much Project MMO xp awarded when chopping player-placed logs

### ISSUE THREAD

**Issue by hammertater** [hammertater/treechop#38]
Project MMO normally reduces XP awarded for breaking player-placed blocks. That's not happening when chopping.

**Comment by cheshyrp** [comment]
Is this really a problem, though? AFAIK, you don't get enough XP for chopping down trees with Tree Chop enabled, as you're only chopping a small percentage of the actual tree's volume. It took me a very long time just to reach 30.

**Comment by hammertater** [comment]
Hey, that's a good point. I'll consider awarding some extra XP when chopping (see #78).

Still, Project MMO does discourage "farming XP" by reducing how much XP is given when breaking player-placed blocks, and TreeChop currently doesn't respect that. Realistically, though, this issue probably won't get fixed -- Project MMO's method for detecting player-placed blocks is pretty sketchy, last I checked. Although, if I do get around to fixing this issue, I'll be sure to first add an option for awarding extra XP when chopping to compensate.

**Comment by KatoNamus** [comment]
I could've sworn I was getting PMMO Woodcutting XP for each "chop" in 1.18.1 but now I see it's an open issue here. Old age is getting to me...
With that said, +1 bump for wanting this feature implemented.

**Comment by hammertater** [comment]
Version 0.17.0 (only for minecraft 1.19.2 at the moment, but 1.18.2 will come soon) fixes XP awards (players were getting 12 per chop instead of 100) and makes them configurable. I also turned off PMMO's XP reduction for player-placed blocks when chopping -- it doesn't really make sense for chopping.
