### ISSUE TITLE
Hi, me again!

### ISSUE THREAD

**Issue by thedeerirty** [hammertater/treechop#39]
Hey, sorry to bug you, but this mod was throwing a crash when I tried to launch it on a server;
my friends and I are playing as of current, so I will send you a log when no one's online so I can freely crash the server lol

Just making this issue while I can! I think the crash was happening during the preintializing or loading process

**Comment by thedeerirty** [comment]
[latest.log](https://github.com/hammertater/treechop/files/5889022/latest.log)
Here's the log!

**Comment by hammertater** [comment]
Welcome back! This crash is actually already fixed, go ahead and update to 0.12.2 :)

**Comment by thedeerirty** [comment]
man pog, you're quite good at this ^^

just wondering, are there any other projects you do for minecraft mods? Idk you seem like a pretty chill dude so if you were looking for like, some models or anything anytime soon I fancy myself a good modeller ^^
your help has been much kinder than most devs I've met so I feel a bit wanting to repay you

**Comment by hammertater** [comment]
Nice of you to offer! I'm not working on anything right now that needs models, but maybe sometime in the future, for sure. Have you thought about making a resource pack, or a mod that adds decorative blocks/items/critters? Or if you've already have something like that posted online, could you send me a link?

**Comment by thedeerirty** [comment]
I've thought about making add-ons to mods before, but I don't have many people I know who aren't busy with their own projects

As for what I've done, not much yet!

I have done about a third of the models for this [Mod](https://www.curseforge.com/minecraft/mc-mods/jojos-bizarre-survival)
and I've been doing all future models for that creator! He's a chill dude, and its a fun mod.
Personally, my biggest weakpoint is texturing but a few good youtube tutorials could probably teach me how to improve
