### ISSUE TITLE
Make item drops configurable

### ISSUE THREAD

**Issue by hammertater** [hammertater/treechop#48]
Configuration options to add:
- Whether blocks spawn item drops when first chopped
- Whether the original block's item drops should only spawn when the chopped block is destroyed
- Whether chopped logs spawn item drops when chopped
- Whether chopped logs spawn item drops when destroyed

In all cases, item drops will be determined by loot tables.

Things this would enable:
- Chopping could produce wood chips items instead of log items
- Dropping a log item on first chop is a little awkward; it might be preferable to drop it when the chopped block is destroyed

**Comment by IdrisQe** [comment]
Wait, the logs dropping from the first chop is intended?
I honestly thought that was a bug and was just coming to report it.
That definitely needs to be changed, it feels wrong on so many levels to tap a log with an axe and get it while the block is still *technically* there, just changed.

**Comment by hammertater** [comment]
I agree, it's disturbing! However, right now the chopped blocks have no memory of what kind of block they used to be (this is why a weird generic texture is used), so there's no reliable way to say what items they should drop. Making this possible is a big priority. The main reason I'd add the option "Whether blocks spawn item drops when first chopped" is to preserve original mod behavior.

**Comment by IdrisQe** [comment]
Ohhhh I see! Also, on the topic of the generic texture, I'm not sure if it's possible, but once the block can remember what it was, it would make a lot of sense to use the Stripped variant of whatever wood you're cutting (or a fallback texture if a stripped variant can't be located)
