### ISSUE TITLE
Crash with SimpleFarming when a fruit tree log is broken

### ISSUE THREAD

**Issue by ChrissPz** [hammertater/treechop#5]
---- Minecraft Crash Report ----
// My bad.

Time: 28-11-20 20:24
Description: Exception in server tick loop

java.lang.NoSuchMethodError: net.minecraft.block.Block.func_180637_b(Lnet/minecraft/world/World;Lnet/minecraft/util/math/BlockPos;I)V
	at ht.treechop.TreeChopMod.dropExperience(TreeChopMod.java:121) ~[?:0.7] {re:classloading}
	at ht.treechop.TreeChopMod.onBreakEvent(TreeChopMod.java:90) ~[?:0.7] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_5_TreeChopMod_onBreakEvent_BreakEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onBlockBreakEvent(ForgeHooks.java:566) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_180237_b(PlayerInteractionManager.java:230) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_229860_a_(PlayerInteractionManager.java:220) ~[?:?] {re:classloading}
	at net.minecraft.server.management.PlayerInteractionManager.func_225416_a(PlayerInteractionManager.java:190) ~[?:?] {re:classloading}
	at net.minecraft.network.play.ServerPlayNetHandler.func_147345_a(ServerPlayNetHandler.java:929) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:40) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerDiggingPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil$$Lambda$8375/2103535327.run(Unknown Source) ~[?:?] {}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:733) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:716) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:710) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:695) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:645) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
	at net.minecraft.server.MinecraftServer$$Lambda$7381/885270011.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2229338872 bytes (2126 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
	CPUs: 8
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.6.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.6.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.6.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.6.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.6.jar fml TRANSFORMATIONSERVICE 
		/MixinBootstrap-1.0.5.jar mixinbootstrap TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.6
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		TreeChop-1.16.1-0.7.jar                           |treechop                      |treechop                      |0.7                 |DONE      |NOSIGNATURE
		ClientTweaks_1.16.3-5.2.0.jar                     |Client Tweaks                 |clienttweaks                  |5.2.0               |DONE      |NOSIGNATURE
		AlwaysEat-4.0.jar                                 |AlwaysEat                     |salwayseat                    |4.0                 |DONE      |NOSIGNATURE
		TrashSlot_1.16.3-12.2.1.jar                       |TrashSlot                     |trashslot                     |12.2.1              |DONE      |NOSIGNATURE
		mining-helmet-1.16.4-2.0.0.jar                    |Mining Helmet                 |mining_helmet                 |2.0.0               |DONE      |NOSIGNATURE
		Trophy+Slots-7.2.0.jar                            |Trophy Slots                  |trophyslots                   |7.2.0               |DONE      |NOSIGNATURE
		RemoveMouseoverHighlight-0.0.1+[1.16.3-34.1.0].jar|Remove Mouseover Highlight    |rmh                           |0.0.1 [1.16.3-34.1.0|DONE      |NOSIGNATURE
		jei-1.16.4-7.6.0.58.jar                           |Just Enough Items             |jei                           |7.6.0.58            |DONE      |NOSIGNATURE
		AttributeFix-1.16.4-9.0.2.jar                     |AttributeFix                  |attributefix                  |9.0.2               |DONE      |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		strawgolem-1.16-1.9.jar                           |Straw Golem                   |strawgolem                    |1.16-1.9            |DONE      |NOSIGNATURE
		BetterCaves-1.16.3-1.0.5.jar                      |YUNG's Better Caves           |bettercaves                   |1.16.3-1.0.5        |DONE      |NOSIGNATURE
		totaldarkness-1.2-1.16.3.jar                      |Total Darkness                |totaldarkness                 |1.2-1.16.3          |DONE      |NOSIGNATURE
		GravelMiner_1.16.3-10.2.0.jar                     |GravelMiner                   |gravelminer                   |10.2.0              |DONE      |NOSIGNATURE
		softerhayb_1.16.4-1.1.jar                         |Softer Hay Bales              |softerhayb                    |1.1                 |DONE      |NOSIGNATURE
		Clumps-6.0.0.12.jar                               |Clumps                        |clumps                        |6.0.0.12            |DONE      |NOSIGNATURE
		backslot-1.16.3-1.2.0.0.jar                       |�cBack �9Slot                 |backslot                      |1.16.3-1.2.0.0      |DONE      |NOSIGNATURE
		EnhancedVisuals_v1.3.19_mc1.16.3.jar              |EnhancedVisuals               |enhancedvisuals               |1.3.0               |DONE      |NOSIGNATURE
		Placebo-1.16.3-4.3.3.jar                          |Placebo                       |placebo                       |4.3.3               |DONE      |NOSIGNATURE
		Bookshelf-1.16.4-9.1.13.jar                       |Bookshelf                     |bookshelf                     |9.1.13              |DONE      |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		BotanyPots-1.16.4-6.0.6.jar                       |BotanyPots                    |botanypots                    |6.0.6               |DONE      |ea:45:b3:82:b6:9d:50:16:95:e7:2e:34:e1:92:d5:b4:9b:69:90:d3:4f:2e:71:99:b0:be:40:80:27:1f:3e:b0
		snowundertrees-1.16.3-v1.1.2.jar                  |Snow Under Trees              |snowundertrees                |v1.1.2              |DONE      |NOSIGNATURE
		pollinatlor-1.16.x-1.0.1.jar                      |Pollinator                    |pollinator                    |1.16.x-1.0.1        |DONE      |NOSIGNATURE
		PickUpNotifier-v1.2-1.16.3.jar                    |Pick Up Notifier              |pickupnotifier                |1.2                 |DONE      |d3:cc:6f:1b:30:87:fa:d9:8f:91:15:20:27:63:95:aa:d5:cb:1b:5b:e6:36:cc:57:20:a9:b3:d4:d5:1a:5d:b8
		Omni-1.16.4-1.1.7.jar                             |Omni                          |omni                          |version             |DONE      |NOSIGNATURE
		Toast-Control-1.16.3-4.3.0.jar                    |Toast Control                 |toastcontrol                  |4.3.0               |DONE      |NOSIGNATURE
		SnowRealMagic-1.16.3-2.2.1.jar                    |Snow! Real Magic!             |snowrealmagic                 |2.2.1               |DONE      |NOSIGNATURE
		Kiwi-1.16.3-3.4.1.jar                             |Kiwi                          |kiwi                          |3.4.1               |DONE      |NOSIGNATURE
		FpsReducer-mc1.16.4-1.18.jar                      |FPS Reducer                   |fpsreducer                    |mc1.16.4-1.18       |DONE      |NOSIGNATURE
		JustEnoughResources-1.16.4-0.12.0.103.jar         |Just Enough Resources         |jeresources                   |0.12.0.103          |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.6-universal.jar                 |Forge                         |forge                         |35.1.6              |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Waddles-1.16.4-0.8.11.jar                         |Waddles                       |waddles                       |1.16.4-0.8.11       |DONE      |NOSIGNATURE
		stackrefill_1.16.4-1.1.jar                        |Stack Refill                  |stackrefill                   |1.1                 |DONE      |NOSIGNATURE
		scuba-gear-1.16.4-1.0.1.jar                       |Scuba Gear                    |scuba_gear                    |1.0.1               |DONE      |NOSIGNATURE
		ConsoleExperience-v1.6-1.16.2.jar                 |Console Experience            |consoleexperience             |1.6                 |DONE      |d3:cc:6f:1b:30:87:fa:d9:8f:91:15:20:27:63:95:aa:d5:cb:1b:5b:e6:36:cc:57:20:a9:b3:d4:d5:1a:5d:b8
		forge-1.16.4-35.1.6-client.jar                    |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		logprot-1.16-1.3.jar                              |Logprot                       |logprot                       |1.3                 |DONE      |NOSIGNATURE
		FarmersDelight-1.16.3-0.2.3.jar                   |Farmer's Delight              |farmersdelight                |1.16.3-0.2.3        |DONE      |NOSIGNATURE
		bloom-and-gloom-0.1.jar                           |Bloom and Gloom               |bloom_and_gloom               |0.1                 |DONE      |NOSIGNATURE
		AmbientSounds_v3.1.2_mc1.16.4.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |NOSIGNATURE
		BiomesOPlenty-1.16.4-13.0.0.421-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.4-13.0.0.418   |DONE      |NOSIGNATURE
		toughnessbar-6.0.jar                              |Toughness Bar                 |toughnessbar                  |6.0                 |DONE      |NOSIGNATURE
		CreativeCore_v2.0.7_mc1.16.2.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      |NOSIGNATURE
		rare-ice-0.2.2.jar                                |Rare Ice                      |rare-ice                      |version             |DONE      |NOSIGNATURE
		simplefarming-1.16.4-1.3.5.jar                    |Simple Farming                |simplefarming                 |1.16.4-1.3.5        |DONE      |NOSIGNATURE
		EyesInTheDarkness-1.16.3-0.7.0.jar                |Eyes in the Darkness          |eyesinthedarkness             |0.7.0               |DONE      |NOSIGNATURE
		xercamod-1.16.3-1.1.jar                           |Xerca Mod                     |xercamod                      |1.16.3-1.1          |DONE      |NOSIGNATURE
		randomite-1.16.4-1.0.1.jar                        |Randomite Classic             |randomite                     |1.0.1               |DONE      |NOSIGNATURE
		gravestone-1.16.4-1.0.5.jar                       |Gravestone Mod                |gravestone                    |1.16.4-1.0.5        |DONE      |NOSIGNATURE
		collective-1.16.4-1.53.jar                        |Collective                    |collective                    |1.53                |DONE      |NOSIGNATURE
		betterweather-1.0.3.jar                           |Better Weather                |betterweather                 |1.0.1               |DONE      |NOSIGNATURE
		FastWorkbench-1.16.3-4.4.1.jar                    |FastWorkbench                 |fastbench                     |4.4.1               |DONE      |NOSIGNATURE
		AutoRegLib-1.6-46.jar                             |AutoRegLib                    |autoreglib                    |1.6-46              |DONE      |NOSIGNATURE
		Quark-r2.4-276.jar                                |Quark                         |quark                         |r2.4-276            |DONE      |NOSIGNATURE
		direbats-1.0.0+1.16.3-forge.jar                   |Direbats                      |direbats                      |1.0.0+1.16.3-forge  |DONE      |NOSIGNATURE
		globaldataandresourcepacks-1.16.1-1.7.2.jar       |Global Data- & Resourcepacks  |globaldataandresourcepacks    |1.16.1-1.7.2        |DONE      |NOSIGNATURE
		FastFurnace-1.16.3-4.3.0.jar                      |FastFurnace                   |fastfurnace                   |4.3.0               |DONE      |NOSIGNATURE
		AppleSkin-mc1.16.2-forge-1.0.14.jar               |AppleSkin                     |appleskin                     |1.0.14              |DONE      |NOSIGNATURE
		ItemPhysic_v1.4.8_mc1.16.4.jar                    |ItemPhysic                    |itemphysic                    |1.6.0               |DONE      |NOSIGNATURE
		DamageTilt-1.16-forge-0.1.1.jar                   |DamageTilt                    |damagetilt                    |0.1.1               |DONE      |NOSIGNATURE
		ProPlacer-v1.0-1.16.2.jar                         |Pro Placer                    |proplacer                     |1.0                 |DONE      |d3:cc:6f:1b:30:87:fa:d9:8f:91:15:20:27:63:95:aa:d5:cb:1b:5b:e6:36:cc:57:20:a9:b3:d4:d5:1a:5d:b8
		water-erosion-1.16.4-forge-1.1.2.jar              |Water Erosion                 |water-erosion                 |1.1.2               |DONE      |NOSIGNATURE
		byg-1.1.5.jar                                     |Oh The Biomes You'll Go       |byg                           |1.1.5               |DONE      |NOSIGNATURE
		TrampleStopper-2.4.7+mc-1.16.4.jar                |Trample Stopper               |tramplestopper                |2.4.7+mc-1.16.4     |DONE      |23:8f:95:0f:65:ec:2e:38:99:79:f4:bc:47:8a:0b:df:29:ef:2d:82:66:20:09:20:02:dc:4a:15:97:45:f8:43
		InventoryEssentials_1.16.3-2.3.0.jar              |Inventory Essentials          |inventoryessentials           |2.3.0               |DONE      |NOSIGNATURE
		[1.16.2][Forge]+RPG-HUD-3.8.2.jar                 |RPG-Hud                       |rpg-hud                       |3.8.2               |DONE      |NOSIGNATURE
		SoundFilters-0.14_for_1.16.2.jar                  |Sound Filters                 |soundfilters                  |0.14_for_1.16.2     |DONE      |NOSIGNATURE
		overloadedarmorbar-5.1.0.jar                      |Overloaded Armor Bar          |overloadedarmorbar            |5.1.0               |DONE      |NOSIGNATURE
		BetterMineshafts-Forge-1.16.3-1.1.jar             |YUNG's Better Mineshafts      |bettermineshafts              |1.16.3-1.1          |DONE      |NOSIGNATURE
		BetterAdvancements-1.16.4-0.1.0.103.jar           |Better Advancements           |betteradvancements            |0.1.0.103           |DONE      |NOSIGNATURE
	Crash Report UUID: 63c5da6f-65c2-4258-9b00-2afb187d96c5
	Kiwi Modules: 
		kiwi:contributors
		kiwi:data
		snowrealmagic:core
		snowrealmagic:world
	Player Count: 1 / 8; [ServerPlayerEntity['RayWoss'/194, l='ServerLevel[New World]', x=267.79, y=70.00, z=-14.80]]
	Data Packs: vanilla, mod:treechop, mod:clienttweaks (incompatible), mod:salwayseat (incompatible), mod:trashslot (incompatible), mod:mining_helmet (incompatible), mod:trophyslots (incompatible), mod:rmh, mod:jei, mod:attributefix, mod:strawgolem, mod:bettercaves (incompatible), mod:totaldarkness, mod:gravelminer (incompatible), mod:softerhayb, mod:clumps (incompatible), mod:backslot, mod:enhancedvisuals (incompatible), mod:placebo (incompatible), mod:bookshelf, mod:botanypots, mod:snowundertrees, mod:pollinator (incompatible), mod:pickupnotifier (incompatible), mod:omni, mod:toastcontrol (incompatible), mod:snowrealmagic, mod:kiwi (incompatible), mod:fpsreducer, mod:jeresources, mod:forge, mod:waddles, mod:stackrefill, mod:scuba_gear (incompatible), mod:consoleexperience, mod:logprot (incompatible), mod:farmersdelight, mod:bloom_and_gloom, mod:ambientsounds (incompatible), mod:biomesoplenty, mod:toughnessbar (incompatible), mod:creativecore (incompatible), mod:rare-ice (incompatible), mod:simplefarming, mod:eyesinthedarkness (incompatible), mod:xercamod (incompatible), mod:randomite (incompatible), mod:gravestone, mod:collective, mod:betterweather (incompatible), mod:fastbench (incompatible), mod:autoreglib (incompatible), mod:quark (incompatible), mod:direbats, mod:globaldataandresourcepacks (incompatible), mod:fastfurnace (incompatible), mod:appleskin, mod:itemphysic (incompatible), mod:damagetilt (incompatible), mod:proplacer, mod:water-erosion (incompatible), mod:byg, mod:tramplestopper (incompatible), mod:inventoryessentials (incompatible), mod:rpg-hud (incompatible), mod:soundfilters (incompatible), mod:overloadedarmorbar (incompatible), mod:bettermineshafts (incompatible), mod:betteradvancements
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by hammertater** [comment]
Hi Chriss, looks like you’ve got the 1.16.1 version installed. Could you try again with the 1.16.4 (here and on curseforge) and let me know if that helps?

**Comment by ChrissPz** [comment]
exactly, I was using a previous version but you have already fix the crash so there is no problem ¯\_(^‿^)_/¯

**Comment by hammertater** [comment]
Glad to hear! I'm gonna close this issue then 👍
