### ISSUE TITLE
Add server-side config override for "onlyBreakTreesWithLeaves".

### ISSUE THREAD

**Issue by Enantiomorph** [hammertater/treechop#50]
As an administrator I would like to be able to disable this functionality for all players on the server.

**Comment by hammertater** [comment]
Sorry for taking so long. I’m fleshing out the “permissions” section of the server config to allow the server to override gameplay-related settings. It’ll look something like this:

‘’’toml
[permissions]
    [permissions.treesMustHaveLeaves]
        canBeTrue = true
        canBeFalse = true

    [permissions.choppingEnabled]
        canBeTrue = true
        canBeFalse = true
        
    ....
‘’’

Note that “onlyBreakTreesWithLeaves” has changed to “treesMustHaveLeaves”. So if you want to force “treesMustHaveLeaves = true”, just set “canBeFalse = false” (or set “canBeTrue = false” to force “treesMustHaveLeaves = false” for players). It’s set up this way to accommodate options that have more than two possible values.

I want to fix a few bugs before I release a new version, so it’s not out yet.

**Comment by hammertater** [comment]
Version 0,14,0 adds configurable permissions. Sorry for the wait! It's only for 1.16.4 right now, but it will make it's way to the 1.12.2 version soon.
