### ISSUE TITLE
Let different players chop the same block at the same time

### ISSUE THREAD

**Issue by hammertater** [hammertater/treechop#52]
...is this feasible? Right now, I think, when a block is chopped, the break progress of other players gets reset. Can we stop that from happening?

**Comment by jarocajavi** [comment]
Great idea, if this has posible will be awesome for chop redwood or bigger trees with friends

**Comment by hammertater** [comment]
Closing, this can be done using Multi Mine (https://www.curseforge.com/minecraft/mc-mods/multi-mine) for Minecraft 1.19+
