### ISSUE TITLE
Suggestion: Tree detection using non-persistent leaves config option

### ISSUE THREAD

**Issue by IdrisQe** [hammertater/treechop#53]
I've seen this in a mod or datapack in the past and it was very useful, and since you already have a way to detect if a tree is connected to persistent leaves to optionally break them, this shouldn't be hard to implement as a config option!

The idea is with this config option set, the chopping would only occur on log blocks connected directly to NON-persistent leaves. That way if you have it set to only chop trees connected to leaves, you won't start to cut down your house accidentally by adding some foliage around as decoration! And since players can't place non-persistent leaves normally, this solves a lot of issues.
The only problem would be growing a tree too close to your house, though that in combination with the leaf "distance" algorithm would probably prevent  most damage to the structure when chopping said tree, only maybe leaving some leaves.

(Also, just wanted to add, fantastic mod! This is the kind of visual I'd always hoped to see in tree chopping mods! Now we just need Dynamic Trees for 1.16.4 and compatability with this for the ultimate lumberjack experience!)

**Comment by hammertater** [comment]
Thanks for posting here! And sorry for taking so long to respond.

I think what you suggest should be the default behavior. I'll make sure this makes it into the next feature update.

> (Also, just wanted to add, fantastic mod! This is the kind of visual I'd always hoped to see in tree chopping mods! Now we just need Dynamic Trees for 1.16.4 and compatability with this for the ultimate lumberjack experience!)

Glad to hear! Someday I'll definitely look into Dynamic Trees compatibility. I'll post any progress on this front in #61.

**Comment by hammertater** [comment]
As of 0.14.0, the default configuration is now ignores persistent leaves. The configuration setting for this has been renamed to `ignorePersistentLeaves` in treechop-common.toml. I'm gonna go ahead and close this issue now. Happy chopping!
