### ISSUE TITLE
[suggestion] Hammer + works on rocks and ores

### ISSUE THREAD

**Issue by HenryMaxler** [hammertater/treechop#54]
I don't know how hard it would be but, seeing the logs chop into smaller logs got me thinking, what if it could work with stone and ores somehow?  The stone could crack and have a 3d model instantly and then break or crack more then break and also work with hammers in a 3x3 area or work with other mod hammers.

If it doesn't make sense maybe it would be better if it mined 3x3x2 deep, and the struck rocks heal after a certain time period if abandoned.

**Comment by hammertater** [comment]
Welcome back Henry! Sorry for not responding! I’ve definitely thought about making a vein-mining or digging-in-general mechanic. I like to make physics-inspired stuff, so maybe it would be fun to add a structural integrity mechanic, where blocks without enough support will collapse (this could make digging easier in certain situations, or with some creativity).

Anyways, I’m pretty busy these days, so it will probably be a while before I start working on a new mod.

**Comment by HenryMaxler** [comment]
Yeah that seems neat.  There have been some gases and collapsing mods I remember.  Might be a good idea if the gas explodes it causes a cave in or something.  TNT is not used for mining that much either.  I thought it would be cool if there was some mechanic like you know when a reactor blows up it leaves a crater?  What about something like that but you block off some parts with obsidian so it it focused like a laser and used for something?  The gas mod was neat I remember because it had a davy lamp and everything.  The physics mod had blocks topple over other blocks sometimes, creating pyramids.  It was pretty wild, you could get caught in a landslide almost iirc
