### ISSUE TITLE
Incompatibility With Misty World

### ISSUE THREAD

**Issue by big-poppy** [hammertater/treechop#56]
#### Issue Description:

Incompatibility between HT's Treechop and the Misty World mod. I went to mine a block of foggy stone with a niobium pickaxe and received a potential problem error from Vanilla Fix between the aforementioned mods.

#### What happens:
Mine a block of foggy stone with a niobium pickaxe, watch it create a ghost block. This issue is similar to my previously reported issue between EnderIO and Treechop.

#### What you expected to happen:
Mine block of foggy stone with a niobium pickaxe and it drops its block in item form.

#### Steps to reproduce:

1. Acquire niobium by any means
2. Attempt to mine a block of foggy stone with your niobium pickaxe
3. 
...

____
#### Affected Versions:

- HT's Treechop: Treechop-1.12.2-0.11.4
- Misty World: MistyWorld-1.12.2-1.2.5.3
- Minecraft: 1.12.2
- Forge: 14.23.5.2855
- SpongeForge? no
- Optifine? no
- Single Player and/or Server? Single Player

#### Most recent log file where the issue was present: 

[latest.log](https://github.com/hammertater/treechop/files/6087642/latest.log)

**Comment by hammertater** [comment]
Thanks for reporting this! Sorry, I’ve been busy lately, but I’ll look into this when I can.

**Comment by hammertater** [comment]
This should be fixed as of 0.14.1. Sorry for the wait!
