### ISSUE TITLE
Error/Possible Crash with FutureMC 1.12.2

### ISSUE THREAD

**Issue by criscky** [hammertater/treechop#58]
Steps to reproduce:
Plant sweet berries from future MC, put log next to it, try break log, see console, the error will be there

Forge 2854
future mc 0.2.6.1
treechop 0.11.4

[error.txt](https://github.com/hammertater/treechop/files/6253033/error.txt)

**Comment by hammertater** [comment]
Thanks for the info, I'll try to fix this ASAP.

**Comment by criscky** [comment]
some update
if you put thermal's ducts next to it, it will make another bug and even crash servers for what i saw

**Comment by hammertater** [comment]
Yikes -- thanks for the update

**Comment by hammertater** [comment]
This should be fixed as of 0.14.1. Sorry for the wait!

**Comment by criscky** [comment]
it seems fixed, sorry for the late close.
if we find any more bugs, i'll make a new report
