### ISSUE TITLE
Tinkers Construct Axe Incompatible

### ISSUE THREAD

**Issue by pinkyboy910** [hammertater/treechop#59]
The Tinker's Construct Axe just breaks the block instead of what happens with fists and with axes.
MC 1.16.5 (Forge 36.1.4)
Tinkers Construct 3.0.2.73
TreeChop 0.13.0

**Comment by hammertater** [comment]
Tinker's Construct for 1.16.5? Oh me oh my!

Thanks for bringing this to my attention, I'll look into it shortly.

**Comment by hammertater** [comment]
Fixed in 0.14.0
