### ISSUE TITLE
1.12.2 Sponge server & apples overspawning

### ISSUE THREAD

**Issue by Mnesikos** [hammertater/treechop#63]
Honestly I don't even know where to begin with this issue report and I am dreadfully sorry in advance lol.

With TreeChop chopping on, cutting down a dark oak tree spawns _several stacks worth_ of apples. Not all at once, but per each block "break." One tree nearly filled three double chests alone. Disabling chopping breaks the logs normally without any apple issues.

I have quite a few mods installed (I'll list these at the end of this report), have tested this on both single player and on a dedicated server, and only on dark oak vs oak trees. This only happens on the server and only with the dark oak trees. Turning off breakLeaves in TreeChop's config does not fix this. I am currently _unsure_ if this is specifically spongeforge related or if it also occurs on a forge server.

Here are the debug and latest logs, however I'm fairly certain they don't contain anything useful.
[debug.log](https://github.com/hammertater/treechop/files/6294820/debug.log)
[latest.log](https://github.com/hammertater/treechop/files/6294821/latest.log)

Finally, the main mod list;
- treechop 0.11.4
- forge 14.23.5.2854
- spongeforge 2838-7.3.0
- biomes o' plenty 7.0.1.2444

the plugins;
- catclearlag 0.9.5.1 (tested without!)
- luckperms 5.3.16
- magibridge 2.11.1
- nucleus 2.3.2

[full_modlist.txt](https://github.com/hammertater/treechop/files/6294901/modlist.txt)

I do apologize that I don't have any more information on this, just hadn't run into the issue until cutting down dark oak trees for the first time today... lmao. Let me know if there's anything else I can do to help!

**Comment by hammertater** [comment]
What a wonderful bug! Sounds like TreeChop is triggering break events somehow during tree detection. Could I get your config files for treechop? There might be more than one (a “common” and a “client”) but I don’t remember whether that’s the case for 1.12.2. They should help me narrow down the problem. Thanks!

**Comment by Mnesikos** [comment]
Ahaha wonderful indeed. So I have one config for treechop from the server's files, as far as I can tell; [treechop.txt](https://github.com/hammertater/treechop/files/6307413/treechop.txt). I don't believe much was edited from default if anything, hopefully it helps!

**Comment by hammertater** [comment]
I haven't tried very hard at recreating this bug, but I have a feeling it should be fixed in the new version (0.14.1). A lot of the code has been rewritten. There were some questionable things in the old version that probably caused wonky issues like this. Sorry for the wait!

**Comment by Mnesikos** [comment]
Totally understood, no worries!! I'll try to test out the new version asap and let you know for sure.

**Comment by hammertater** [comment]
As much as I love this issue, I'm gonna assume it's fixed and close. Feel free to reopen if needed
