### ISSUE TITLE
Maybe exclude fake players from chopping functionality to reduce cross-mod issues

### ISSUE THREAD

**Issue by TheRealWormbo** [hammertater/treechop#71]
I noticed quite a severe interaction between the RFTools Builder and Treechop when the builder is in filtered quarry mode. It appears the builder touches many blocks it then decides to not actually harvest, triggering Treechop to do a bunch of leaf clearing and log chopping, when any of the touched blocks are logs. Now I'm not saying this interaction is Treechop's fault (it's more that the builder should probably not attempt to break blocks it doesn't care about in the first place), but the builder, like several other mods, uses a fake player to do its work. Maybe it would help Treechop prevent further inconvenient interactions like that by simply not applying its logic when a fake player does the chopping. (It already doesn't apply when a contraption without any kind of player does the block breaking.)

Example screenshot of this interaction:
![2021-05-24_08 38 15](https://user-images.githubusercontent.com/7620864/119494146-43afbc80-bd61-11eb-8baa-f8ac951fae22.png)
The RFTools Builder was set to mine in a relatively large area, but only collect certain ores and leave everything else as it was.

Related bug report on RFTools Builder: [Tree decapitations and other cases of mods seeing the builder breaking blocks when it doesn't break them](https://github.com/McJtyMods/RFToolsBuilder/issues/57)

**Comment by hammertater** [comment]
Hi Wombo, that's terrifying! Thanks for reporting this. Ignoring fake players would definitely fix this, so I'll add that.

Though, I will add a configuration option to re-enable this - I intentionally didn't ignore fake players because I was hoping things like TNT and block-breaking-things from other mods could trigger chopping, leading to some more pleasant mod interactions.

**Comment by hammertater** [comment]
Version 0,14,2 is up and ignores fake players by default. I'm gonna go ahead and close this issue. Thanks again!
