### ISSUE TITLE
No Jungle Saplings

### ISSUE THREAD

**Issue by danemorgan** [hammertater/treechop#74]
Minecraft 1.16.5
Forge 36.1.32
TreeChop-1.16.4-0.14.4.jar

I've chopped 10 Jungle trees with this and gotten zero saplings. Oak, Dark Oak, and Birch are all dropping saplings as normal.

**Comment by danemorgan** [comment]
And on the eleventh tree, I got two. I guess it was just really unlucky RNG.

**Comment by hammertater** [comment]
Yeah, that is absolutely terrible RNG haha. Thanks for trying an 11th time. Glad it seems to be working!
