### ISSUE TITLE
Can i chop more times than all quantity of block has the tree?

### ISSUE THREAD

**Issue by jarocajavi** [hammertater/treechop#76]
Hello, maybe a did not understand the config file, but i can't set a configuration wich add a few chops per block.

I want chop 1,5 times of total block of tree. I think the maximum now is 1.0

**Comment by hammertater** [comment]
Hey, you're right, the limit is currently 1.0. Sorry about that! I'll increase it to 7.0, since that's the currently maximum number of times you can chop an individual block.

**Comment by jarocajavi** [comment]
Thanks so much for the fast answer, i will wait with desire :)

**Comment by hammertater** [comment]
TreeChop 0.14.5 is posted on CurseForge and should let you set values higher than 1.0 now. I've only updated the Minecraft 1.16.3-1.16.5 version though, but if you use an earlier version, I'll be happy to update that too

**Comment by jarocajavi** [comment]
Niiiiice, thanks so much for the support my friend, i will go to tested right now. :D

**Comment by jarocajavi** [comment]
[chopCounting.linear]
		#The base number of chops required to fell a tree regardless of its size
		#Range: -10000.0 ~ 10000.0
		baseNumChops = 0.0
		#The number of chops per block required to fell a tree; if chopsPerBlock = 0.5, it will take 50 chops to fell a 100 block tree
		#Range: 0.0 ~ 1.0
		chopsPerBlock = 1.5
		
		
		
		Is like that, right?

**Comment by jarocajavi** [comment]
automatically it change to 1.0 😵‍💫

**Comment by hammertater** [comment]
I'm so sorry! I made a silly typo! This will be fixed in the next update

**Comment by hammertater** [comment]
All right... it's finally fixed in TreeChop-1.16.4-0.14.6-fixed. Sorry this took so long.

**Comment by jarocajavi** [comment]
> All right... it's finally fixed in TreeChop-1.16.4-0.14.6-fixed. Sorry this took so long.

Sorry, im 4 months late :( I left the server project for a while, but im here again with another server and obviously, with your mod and fixes. Thanks so much for your time to solved the problem i tell you.
