### ISSUE TITLE
Missing loot table for chopped_log

### ISSUE THREAD

**Issue by cheshyrp** [hammertater/treechop#77]
According to Blame, the loot table is missing or incorrect for the chopped log block.

****************** Blame Report 1.16.5-3.2.3-forge ******************

 Found a Loot Table path that does not exist:  treechop:blocks/chopped_log
 The path represented by this Loot Table is:  data/treechop/loot_tables/blocks/chopped_log.json
 Loot Table method called at:  net.minecraft.block.AbstractBlock.func_220076_a
                               net.minecraft.block.AbstractBlock$AbstractBlockState.func_215693_a
 Most common cause is that the Loot Table file is not actually at that location.
 Please let the mod author know about this so they can check to see if their Loot Table is correct.

**Comment by hammertater** [comment]
Thanks for reporting this, I'll take care of it soon

**Comment by cheshyrp** [comment]
You're welcome

**Comment by hammertater** [comment]
Version 0.14.5 on CurseForge should now include the missing loot table. I haven't confirmed using Blame though, so please let me know if the message still appears
