### ISSUE TITLE
[Question] Will you be backporting Fakeplayer chopping config to 1.12.2?

### ISSUE THREAD

**Issue by anabsolutesloth** [hammertater/treechop#79]
It's a well known bother for the MC Eternal modpack community, i see it's only been applied to versions of the mod for newer versions of Minecraft, and not 1.12.

**Comment by Feky** [comment]
That would be awesome! 👍

**Comment by hammertater** [comment]
Thanks for reporting this. I've included FakePlayer chopping in version 0.14.6 for Minecraft 1.12.2
