### ISSUE TITLE
Server crash when using terrasteel axe from botania

### ISSUE THREAD

**Issue by SirChubb** [hammertater/treechop#80]
Server crashes every time my friend uses his terrasteel axe to cut trees down when he has this mod enabled. If he deactivates it with the hotkey there are no problems. Only noticed this problem since we updated the MC Eternal modpack from 1.4.4 to 1.5. The mods of the MCEternal told me to post here as well.

**Comment by hammertater** [comment]
Thanks for reporting. I’ll look into this soon

**Comment by hammertater** [comment]
Sorry for the wait. A quick fix is to open the `config/treechop-common.toml` file and add "botania:terra_axe" to the list under the [compatibility.general.blacklist] section, like this:
```
		[compatibility.general.blacklist]
			#Whether the listed items should be blacklisted or whitelisted
			#Allowed Values: BLACKLIST, WHITELIST
			blacklistOrWhitelist = "BLACKLIST"
			#List of item registry names (mod:item), tags (#mod:tag), and namespaces (@mod) for items that should not chop when used to break a log
			#- Items in this list that have special support for TreeChop will not be blacklisted; see https://github.com/hammertater/treechop/blob/main/docs/compatibility.md#blacklist
			items = ["botania:terra_axe", "mekanism:atomic_disassembler", "@lumberjack", "practicaltools:iron_greataxe", "practicaltools:golden_greataxe", "practicaltools:diamond_greataxe", "practicaltools:netherite_greataxe"]
```

**Comment by hammertater** [comment]
I'll update the mod soon and add the terra axe to the blacklist by default

**Comment by hammertater** [comment]
The blacklist is updated as of 0.14.6. If you do update the mod, be sure to delete the treechop-common.toml file so the fix gets applied
