### ISSUE TITLE
Inconsistent Results

### ISSUE THREAD

**Issue by reddvilzz** [hammertater/treechop#81]
Hi there, I was using Treechop version 0.14.4 on MC Eternal Modpack, and I keep getting inconsistent results when using the mod.

For example, when I just joined the world and try to chop trees, the first hit will always show the mod is working, but at the 2nd chop it will destroy the bark textured tree, which makes the mod disabled, but I can still see the icon for the treechop it's just the function is not working and I need to just wait until it works again in a sudden.

Sometimes I when the mod turned back on again, after a moment it will turned off again.
Looking at the log files doesn't show anything in particular.
I hope you understand my explanation.

Here is the [latest.log](https://github.com/hammertater/treechop/files/7237921/latest.log) (it's quite big)

**Comment by reddvilzz** [comment]
I think I found what causing it, I'm using extended days mod which extends the time of both day and night, sometimes when that mod do it's thing it will make treechop mod not working until certain periode (it's almost consistent) I think it is related to the extended days mod which freezes the sun/moon then resuming it.

**Comment by hammertater** [comment]
Thanks for reporting this! I'll look into this right away

**Comment by hammertater** [comment]
You were right, the extended days mod was causing the conflict. Thanks for suggesting that -- you saved me a lot of time! I'll post an update soon

**Comment by hammertater** [comment]
It's fixed in 0.14.6! Thanks again.
