### ISSUE TITLE
[1.12.2] Fakeplayer Chopping config does not appear to be working

### ISSUE THREAD

**Issue by anabsolutesloth** [hammertater/treechop#84]
https://user-images.githubusercontent.com/63694982/137082882-885f578b-fabd-4a0c-8004-79b386984563.mp4

Set to True at the time of the video, but the exact same result occured when it was False.

**Comment by hammertater** [comment]
Ok, I've confirmed that it's fixed for real this time in 0.14.7. Sorry for the wait... again.

**Comment by anabsolutesloth** [comment]
Appears to work, thank you!
