### ISSUE TITLE
Add compatibility with Watersource mod

### ISSUE THREAD

**Issue by sfiomn** [hammertater/treechop#85]
The trees from Watersource mod https://www.curseforge.com/minecraft/mc-mods/water-source
are not taken into account by Tree Chop, would be great to add this compatibility.

**Comment by hammertater** [comment]
Thanks for reporting! Looks like it's an issue with WaterSource not giving coconut leaves the proper tag. If you turn off TreeChop's "Trees must have leaves" option, you'll be able to cut WaterSource's trees (their leaves aren't being recognized).

**Comment by sfiomn** [comment]
I find this option pretty clever, so when you cut the head of the tree, the rest isn't taken as a tree to cut in once.
It avoids also trees used as pilars to be cut in once.
Do you think it's possible to take into account their leaves ?
Maybe should we report this to water source mod ?
I've also noticed that baobab trees from byg aren't fully cut because some tree blocks have just a corner in common.
Do you think it's possible to add a check if the tree goes in diagonal corner up ?

**Comment by hammertater** [comment]
> Maybe should we report this to water source mod ?

I just reported this to WaterSource in https://github.com/lemon-slice-studio/WaterSource/issues/50

> Do you think it's possible to add a check if the tree goes in diagonal corner up ?

Yeah, it's already checking for upward-diagonal blocks. I think the baobabs are either a) too big or b) have disconnected logs, or logs connected only by leaves. I've added baobabs to the list in #44, so I'll try to fix that eventually

**Comment by sfiomn** [comment]
So great !
Take you so much for your amazing work

**Comment by hammertater** [comment]
The WaterSource folks say they've fixed it on their end, so I'm gonna close this. Thanks again for reporting!
