### ISSUE TITLE
Minor issue with Jade

### ISSUE THREAD

**Issue by zebjamb** [hammertater/treechop#88]
The broken log shows up incorrectly while using Jade, not sure if its an issue with all HWYLA forks.
![image](https://user-images.githubusercontent.com/55518408/147795006-e1d3704b-4fbe-4afd-a721-bc5598bdd7d5.png)

**Comment by hammertater** [comment]
I think it is an issue with all the HWYLAs, just a missing localization text. Thanks for reporting. Will be fixed in the next version!
