### ISSUE TITLE
Add compat with No Tree Punching

### ISSUE THREAD

**Issue by hammertater** [hammertater/treechop#99]
...as mentioned in https://www.curseforge.com/minecraft/mc-mods/treechop?comment=279

No Tree Punching: https://github.com/alcatrazEscapee/no-tree-punching

**Comment by hammertater** [comment]
Added in 0.15.6

**Comment by tbgeorge** [comment]
I'm using version 0.15.7 and this functionality doesn't seem to function correctly. I can still break the log up to the final "chopped" stage and then the rest of the tree (above the chopped block) breaks. Though it leaves the chopped block, that can only be harvested with an axe.

**Comment by hammertater** [comment]
Thanks for reporting. Sorry I didn't notice this til now. I'll look into it

**Comment by hammertater** [comment]
Oof, sorry for the wait... Fixed in TreeChop 0.17.3, currently only for 1.19.2, soon to be backported to 1.18.2.
